apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plex
      app.kubernetes.io/name: plex
  template:
    metadata:
      labels:
        app: plex
        app.kubernetes.io/name: plex
        app.kubernetes.io/part-of: streaming-stack
    spec:
      containers:
        - name: plex
          image: lscr.io/linuxserver/plex:latest
          env:
          - name: VERSION
            value: "docker"
          - name: PLEX_CLAIM
            value: claim-DQMsWFNz7TrFNEzV921y
          - name: LIBVA_DRIVER_NAME
            value: "iHD"
          envFrom:
          - configMapRef:
              name: streaming-stack-config
          ports:
            - containerPort: 32400
          volumeMounts:
            - name: config
              mountPath: /config
            - name: dri
              mountPath: /dev/dri
            - name: movies
              mountPath: /movies
            - name: series
              mountPath: /tv
      nodeSelector:
        kubernetes.io/hostname: castillo
      volumes:
        - name: dri
          hostPath:
            path: /dev/dri
        - name: config
          hostPath:
            path: /mnt/plex
            type: DirectoryOrCreate
        - name: movies
          persistentVolumeClaim:
            claimName: movies-pvc
        - name: series
          persistentVolumeClaim:
            claimName: series-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: plex-lb
  annotations:
    external-dns.alpha.kubernetes.io/hostname: plex.lan
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.37
  selector:
    app: plex
  ports:
    # Puerto principal (web + streaming)
    - name: plex-http
      protocol: TCP
      port: 80
      targetPort: 32400

    # DLNA discovery
    - name: plex-dlna
      protocol: UDP
      port: 1900
      targetPort: 1900

    # mDNS / Bonjour
    - name: plex-mdns
      protocol: UDP
      port: 5353
      targetPort: 5353

    # Plex companion
    - name: plex-companion
      protocol: TCP
      port: 8324
      targetPort: 8324

    # GDM discovery
    - name: plex-gdm-1
      protocol: UDP
      port: 32410
      targetPort: 32410
    - name: plex-gdm-2
      protocol: UDP
      port: 32412
      targetPort: 32412
    - name: plex-gdm-3
      protocol: UDP
      port: 32413
      targetPort: 32413
    - name: plex-gdm-4
      protocol: UDP
      port: 32414
      targetPort: 32414

    # DLNA server
    - name: plex-dlna-tcp
      protocol: TCP
      port: 32469
      targetPort: 32469
  