apiVersion: v1
kind: Service
metadata:
  name: infisical-redis
  labels:
    app: redis
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app.kubernetes.io/name: infisical-redis
  type: ClusterIP
