apiVersion: apps/v1
kind: Deployment
metadata:
  name: infisical-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: infisical-redis
      app.kubernetes.io/name: infisical-redis
  template:
    metadata:
      labels:
        app: infisical-redis
        app.kubernetes.io/name: infisical-redis
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
        resources:
          requests:
            memory: "128Mi"
            cpu: "25m"
