apiVersion: v1
kind: PersistentVolume
metadata:
  name: infisical-postgres-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: /mnt/infiscal-postgresql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: infisical-postgres-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 5Gi
