apiVersion: v1
kind: ConfigMap
metadata:
  name: reactive-db
data:
  DB_NAME: "reactive-resume"
  DB_USER: "reactive-resume"
  DB_PASSWORD: "yq=40sGkjbL76-G."
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: reactive-resume-config
  namespace: default
data:
  # Global
  TZ: "America/Bogota"
  PORT: "3000"
  NODE_ENV: "production"
  APP_URL: "http://resume.lan"

  # Database
  DATABASE_URL: "postgresql://reactive-resume:yq=40sGkjbL76-G.@reactive-resume-postgresql:5432/reactive-resume"
  
  # Chrome Config
  CHROME_URL: "ws://lightpanda.core.svc.cluster.local:9222"

  # Cache
  REDIS_URL: "redis://reactive-resume-valkey:6379"

  # SMTP
  SMTP_SECURE: "true"
  SMTP_FROM: "Citocafecito Resume <resume@citocafecito.work>"

  # Oauth
  OAUTH_PROVIDER_NAME: "Citocafecito Homelab"

  # S3 Storage
  S3_ENDPOINT: "http://garage.storage.svc.cluster.local:3900"
  S3_PORT: "3900"
  S3_REGION: "garage"
  S3_BUCKET: "reactive-resume"
  S3_USE_SSL: "false"
  S3_FORCE_PATH_STYLE : "true"