apiVersion: v1
kind: ConfigMap
metadata:
  name: navidrome-smart-playlists
data:
  # 1. Supermix (Favoritos - Aleatorio)
  supermix.nsp: |
    {
      "name": "Super Mix",
      "comment": "Favoritos y canciones con rating alto en orden aleatorio",
      "all": [
        {
          "any": [
            { "is": { "loved": true } },
            { "gt": { "rating": 3 } }
          ]
        }
      ],
      "sort": "random",
      "limit": 300
    }

  # 2. Super Super Mix (Más escuchados + Favoritos top)
  supersupermix.nsp: |
    {
      "name": "Super Super Mix",
      "comment": "Tus canciones más quemadas y top ratings",
      "all": [
        {
          "any": [
            { "gt": { "rating": 4 } },
            { "gt": { "playCount": 10 } }
          ]
        }
      ],
      "sort": "random",
      "limit": 150
    }

  # 3. Descubrimiento (Nunca escuchadas)
  discovery.nsp: |
    {
      "name": "Descubrimiento",
      "comment": "Joyas de tu librería que aún no has reproducido",
      "all": [
        { "is": { "playCount": 0 } }
      ],
      "sort": "random",
      "limit": 100
    }

  top_80s.nsp: |
    {
      "name": "Top 80s Mix",
      "all": [
        {
          "any": [
            { "is": { "loved": true } },
            { "gt": { "rating": 3 } }
          ]
        },
        { "inTheRange": { "year": [1980, 1989] } }
      ],
      "sort": "random",
      "limit": 50
    }

  top_90s.nsp: |
    {
      "name": "Top 90s Mix",
      "all": [
        {
          "any": [
            { "is": { "loved": true } },
            { "gt": { "rating": 3 } }
          ]
        },
        { "inTheRange": { "year": [1990, 1999] } }
      ],
      "sort": "random",
      "limit": 50
    }

  top_00s.nsp: |
    {
      "name": "Top 00s Mix",
      "all": [
        {
          "any": [
            { "is": { "loved": true } },
            { "gt": { "rating": 3 } }
          ]
        },
        { "inTheRange": { "year": [2000, 2009] } }
      ],
      "sort": "random",
      "limit": 50
    }