apiVersion: v1
kind: ConfigMap
metadata:
  name: navidrome-config
data:
  ND_SCANSCHEDULE: "1h"
  ND_UIWELCOMEMESSAGE: "Bienvenidos a HabiMusic - Música en alta definición"
  ND_SHAREURL: "https://music.citocafecito.work"
  ND_BACKUP_COUNT: "3"
  ND_BACKUP_PATH: "/data/backup"
  ND_ENABLEGRAVATAR: "true"
  ND_DEFAULTLANGUAGE: "es"
  ND_ENABLESHARING: "true"
  ND_LASTFM_LANGUAGE: "es"
  ND_AUTOIMPORTPLAYLISTS: "true"
  ND_PLAYLISTSPATH: "playlists"
  ND_PREFERSORTTAGS: "true"
  ND_SCANNER_PURGEMISSING: "always"
  ND_LYRICSPRIORITY: ".lrc,embedded"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: navidrome-playlists
data:
  Angra-Temple-of-Shadows-20th-Anniversary-Tour.m3u: |
    #EXTM3U
    #PLAYLIST:Angra - Temple of Shadows 20th Anniversary Tour
    #COMMENT: Angra 3h de concierto

    #EXTINF:-1,Nothing to Say
    /music/Angra/(2014) Secret Garden/Angra - Secret Garden - 02 - Nothing to Say.mp3

    #EXTINF:-1,Millennium Sun
    /music/Angra/(2001) Rebirth/Angra - 03 - Millennium Sun.mp3

    #EXTINF:-1,Tide of Changes - Part I
    /music/Angra/(2023) Cycles of Pain/Angra - 04 - Tide of Changes – Part I.flac

    #EXTINF:-1,Tide of Changes - Part II
    /music/Angra/(2023) Cycles of Pain/Angra - 04 - Tide of Changes – Part II.flac

    #EXTINF:-1,Deus le volt!
    /music/Angra/(2004) Temple of Shadows/Angra - 01 - Deus le volt!.mp3

    #EXTINF:-1,Spread Your Fire
    /music/Angra/(2004) Temple of Shadows/Angra - 02 - Spread Your Fire.mp3

    #EXTINF:-1,Angels and Demons
    /music/Angra/(2004) Temple of Shadows/Angra - 03 - Angels and Demons.mp3

    #EXTINF:-1,Waiting Silence
    /music/Angra/(2004) Temple of Shadows/Angra - 04 - Waiting Silence.mp3

    #EXTINF:-1,Wishing Well
    /music/Angra/(2004) Temple of Shadows/Angra - 05 - Wishing Well.mp3

    #EXTINF:-1,The Temple of Hate
    /music/Angra/(2004) Temple of Shadows/Angra - 06 - The Temple of Hate.mp3

    #EXTINF:-1,The Shadow Hunter
    /music/Angra/(2004) Temple of Shadows/Angra - 07 - The Shadow Hunter.mp3

    #EXTINF:-1,No Pain for the Dead
    /music/Angra/(2004) Temple of Shadows/Angra - 08 - No Pain for the Dead.mp3

    #EXTINF:-1,Winds of Destination
    /music/Angra/(2004) Temple of Shadows/Angra - 09 - Winds of Destination.mp3

    #EXTINF:-1,Sprouts of Time
    /music/Angra/(2004) Temple of Shadows/Angra - 10 - Sprouts of Time.mp3

    #EXTINF:-1,Morning Star
    /music/Angra/(2004) Temple of Shadows/Angra - 11 - Morning Star.mp3

    #EXTINF:-1,Late Redemption
    /music/Angra/(2004) Temple of Shadows/Angra - 12 - Late Redemption.mp3

    #EXTINF:-1,Vida Seca
    /music/Angra/(2023) Cycles of Pain/Angra - 06 - Vida seca.flac

    #EXTINF:-1,Rebirth
    /music/Angra/(2014) Secret Garden/Angra - Secret Garden - 10 - Rebirth.mp3

    #EXTINF:-1,Unfinished Allegro
    /music/Angra/(2014) Secret Garden/Angra - Secret Garden - 08 - Unfinished Allegro.mp3

    #EXTINF:-1,Carry On
    /music/Angra/(2014) Secret Garden/Angra - Secret Garden - 09 - Carry On.mp3

    #EXTINF:-1,Nova Era
    /music/Angra/(2014) Secret Garden/Angra - Secret Garden - 11 - Nova era.mp3

    #EXTINF:-1,Gate XIII
    /music/Angra/(2004) Temple of Shadows/Angra - 13 - Gate XIII.mp3

  Iron-Maiden-Future-Past-Tour.m3u: |
    #EXTM3U
    #PLAYLIST:Iron Maiden - The Future Past Tour
    #COMMENT: Setlist basado en archivos locales

    #EXTINF:-1,Caught Somewhere in Time
    /music/Iron Maiden/(1986) Somewhere in Time/Iron Maiden - Somewhere in Time - 01 - Caught Somewhere in Time.flac

    #EXTINF:-1,Stranger in a Strange Land
    /music/Iron Maiden/(1986) Somewhere in Time/Iron Maiden - Somewhere in Time - 06 - Stranger in a Strange Land.flac

    #EXTINF:-1,The Writing on the Wall
    /music/Iron Maiden/(2021) Senjutsu/Iron Maiden - Senjutsu - 03 - The Writing on the Wall.flac

    #EXTINF:-1,Days of Future Past
    /music/Iron Maiden/(2021) Senjutsu/Iron Maiden - Senjutsu - 05 - Days of Future Past.flac

    #EXTINF:-1,The Time Machine
    /music/Iron Maiden/(2021) Senjutsu/Iron Maiden - Senjutsu - 06 - The Time Machine.flac

    #EXTINF:-1,The Prisoner
    /music/Iron Maiden/(1982) The Number of the Beast/Iron Maiden - 03 - The Prisoner.flac

    #EXTINF:-1,Death of the Celts
    /music/Iron Maiden/(2021) Senjutsu/Iron Maiden - Senjutsu - 02 - Death of the Celts.flac

    #EXTINF:-1,Can I Play With Madness
    /music/Iron Maiden/(1988) Seventh Son of a Seventh Son/Iron Maiden - Seventh Son of a Seventh Son - 03 - Can I Play With Madness.flac

    #EXTINF:-1,Heaven Can Wait
    /music/Iron Maiden/(1986) Somewhere in Time/Iron Maiden - Somewhere in Time - 04 - Heaven Can Wait.flac

    #EXTINF:-1,Alexander the Great
    /music/Iron Maiden/(1986) Somewhere in Time/Iron Maiden - Somewhere in Time - 08 - Alexander the Great.flac

    #EXTINF:-1,Fear of the Dark
    /music/Iron Maiden/(1992) Fear of the Dark/Iron Maiden - 12 - Fear of the Dark.mp3

    #EXTINF:-1,Iron Maiden
    /music/Iron Maiden/(1980) Iron Maiden/Iron Maiden - 08 - Iron Maiden.flac

    #EXTINF:-1,Hell on Earth
    /music/Iron Maiden/(2021) Senjutsu/Iron Maiden - Senjutsu - 04 - Hell on Earth.flac

    #EXTINF:-1,The Trooper
    /music/Iron Maiden/(1983) Piece of Mind/Iron Maiden - 05 - The Trooper.flac

    #EXTINF:-1,Wasted Years
    /music/Iron Maiden/(1986) Somewhere in Time/Iron Maiden - Somewhere in Time - 02 - Wasted Years.flac

  Iron-Maiden-Run-For-Your-Lives.m3u: |
    #EXTM3U
    #PLAYLIST:Iron Maiden - Run For Your Lives World Tour (50th Anniversary)
    #COMMENT: Desde Iron Maiden a Fear of the Dark

    #EXTINF:-1,Murders in the Rue Morgue
    /music/Iron Maiden/(1981) Killers/Iron Maiden - 03 - Murders in the Rue Morgue.flac

    #EXTINF:-1,Wrathchild
    /music/Iron Maiden/(1981) Killers/Iron Maiden - 02 - Wrathchild.flac

    #EXTINF:-1,Killers
    /music/Iron Maiden/(1981) Killers/Iron Maiden - 07 - Killers.flac

    #EXTINF:-1,Phantom of the Opera
    /music/Iron Maiden/(1980) Iron Maiden/Iron Maiden - 05 - Phantom of the Opera.flac

    #EXTINF:-1,The Number of the Beast
    /music/Iron Maiden//Iron Maiden - 05 - The Number of the Beast.flac

    #EXTINF:-1,The Clairvoyant
    /music/Iron Maiden/(1988) Seventh Son of a Seventh Son/Iron Maiden - Seventh Son of a Seventh Son - 07 - The Clairvoyant.flac

    #EXTINF:-1,Powerslave
    /music/Iron Maiden/(1984) Powerslave/Iron Maiden - Powerslave - 07 - Powerslave.flac

    #EXTINF:-1,2 Minutes to Midnight
    /music/Iron Maiden/(1984) Powerslave/Iron Maiden - Powerslave - 02 - 2 Minutes to Midnight.flac

    #EXTINF:-1,Rime of the Ancient Mariner
    /music/Iron Maiden/(1984) Powerslave/Iron Maiden - Powerslave - 08 - Rime of the Ancient Mariner.flac

    #EXTINF:-1,Run to the Hills
    /music/Iron Maiden//Iron Maiden - 06 - Run to the Hills.flac

    #EXTINF:-1,Seventh Son of a Seventh Son
    /music/Iron Maiden/(1988) Seventh Son of a Seventh Son/Iron Maiden - Seventh Son of a Seventh Son - 05 - Seventh Son of a Seventh Son.flac

    #EXTINF:-1,The Trooper
    /music/Iron Maiden/(1983) Piece of Mind/Iron Maiden - 05 - The Trooper.flac

    #EXTINF:-1,Hallowed Be Thy Name
    /music/Iron Maiden/(1982) The Number of the Beast/Iron Maiden - 09 - Hallowed Be Thy Name.flac

    #EXTINF:-1,Iron Maiden
    /music/Iron Maiden/(1980) Iron Maiden/Iron Maiden - 08 - Iron Maiden.flac

    #EXTINF:-1,Aces High
    /music/Iron Maiden/(1984) Powerslave/Iron Maiden - Powerslave - 01 - Aces High.flac

    #EXTINF:-1,Fear of the Dark
    /music/Iron Maiden/(1992) Fear of the Dark/Iron Maiden - 12 - Fear of the Dark.mp3

    #EXTINF:-1,Wasted Years
    /music/Iron Maiden/(1986) Somewhere in Time/Iron Maiden - Somewhere in Time - 02 - Wasted Years.flac
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: navidrome-smart-playlists
data:
  Stratovarius-Calle-13-bar-bogota-colombia-2025.m3u: |
    #EXTM3U
    #PLAYLIST:Stratovarius - Live at Calle 13 Bar, Bogota
    #COMMENT: Setlist Power Metal en Bogotá
    #EXTARTIST:Stratovarius
    #EXTGENRE:Power Metal

    #EXTINF:-1,Forever Free
    /music/Stratovarius/(1997) Visions/Stratovarius - 03 - Forever Free.mp3

    #EXTINF:-1,Eagleheart
    /music/Stratovarius/(2003) Elements, Pt. 1/Stratovarius - Elements, Pt. 1 - 01 - Eagleheart.mp3

    #EXTINF:-1,World on Fire
    /music/Stratovarius/(2022) Survive/Stratovarius - 07 - World on Fire.flac

    #EXTINF:-1,Will the Sun Rise?
    /music/Stratovarius/(1996) Episode/Stratovarius - 02 - Will the Sun Rise.flac

    #EXTINF:-1,Distant Skies
    /music/Stratovarius/(1995) Fourth Dimension/Stratovarius - 02 - Distant Skies.mp3

    #EXTINF:-1,Holy Light
    /music/Stratovarius/(1997) Visions/Stratovarius - 07 - Holy Light.mp3

    #EXTINF:-1,Paradise
    /music/Stratovarius/(1997) Visions/Stratovarius - 08 - Paradise.mp3

    #EXTINF:-1,Eternity
    /music/Stratovarius/(1996) Episode/Stratovarius - 03 - Eternity.flac

    #EXTINF:-1,Black Diamond
    /music/Stratovarius/(1997) Visions/Stratovarius - 01 - Black Diamond.mp3

    #EXTINF:-1,Survive
    /music/Stratovarius/(2022) Survive/Stratovarius - 01 - Survive.flac

    #EXTINF:-1,Visions (Southern Cross)
    /music/Stratovarius/(1997) Visions/Stratovarius - 10 - Visions (Southern Cross).mp3

    #EXTINF:-1,Forever
    /music/Stratovarius/(1996) Episode/Stratovarius - 12 - Forever.flac

    #EXTINF:-1,Unbreakable
    /music/Stratovarius/(2013) Nemesis/Stratovarius - 02 - Unbreakable.mp3

    #EXTINF:-1,Hunting High and Low
    /music/Stratovarius/(2000) Infinite/Stratovarius - 01 - Hunting High and Low.mp3
  
  Stratovarius-Best-Of.m3u: |
    #EXTM3U
    #PLAYLIST:Stratovarius - Definitive Collection
    # Rutas relativas a /music/

    #EXTINF:-1,Black Diamond
    /music/Stratovarius/(1997) Visions/Stratovarius - 01 - Black Diamond.mp3

    #EXTINF:-1,Hunting High and Low
    /music/Stratovarius/(2000) Infinite/Stratovarius - 01 - Hunting High and Low.mp3

    #EXTINF:-1,Survive
    /music/Stratovarius/(2022) Survive/Stratovarius - 01 - Survive.flac

    #EXTINF:-1,Father Time
    /music/Stratovarius/(1996) Episode/Stratovarius - 01 - Father Time.flac

    #EXTINF:-1,Eagleheart
    /music/Stratovarius/(2003) Elements, Pt. 1/Stratovarius - Elements, Pt. 1 - 01 - Eagleheart.mp3

    #EXTINF:-1,Unbreakable
    /music/Stratovarius/(2013) Nemesis/Stratovarius - 02 - Unbreakable.mp3

    #EXTINF:-1,Speed of Light
    /music/Stratovarius/(1996) Episode/Stratovarius - 05 - Speed of Light.flac

    #EXTINF:-1,Paradise
    /music/Stratovarius/(1997) Visions/Stratovarius - 08 - Paradise.mp3

    #EXTINF:-1,Destiny
    /music/Stratovarius/(1998) Destiny/Stratovarius - 01 - Destiny.mp3

    #EXTINF:-1,Legions
    /music/Stratovarius/(1997) Visions/Stratovarius - 05 - Legions.mp3

    #EXTINF:-1,Frozen in Time
    /music/Stratovarius/(2022) Survive/Stratovarius - 06 - Frozen in Time.flac

    #EXTINF:-1,World on Fire
    /music/Stratovarius/(2022) Survive/Stratovarius - 07 - World on Fire.flac

    #EXTINF:-1,Forever
    /music/Stratovarius/(1996) Episode/Stratovarius - 12 - Forever.flac

    #EXTINF:-1,The Kiss of Judas
    /music/Stratovarius/(1997) Visions/Stratovarius - 02 - The Kiss of Judas.mp3

    #EXTINF:-1,Shine in the Dark
    /music/Stratovarius/(2015) Eternal/Stratovarius - 02 - Shine in the Dark.mp3

  favorites.nsp: |
    {
      "name": "Favoritos",
      "comment": "Canciones marcadas como favoritas o con rating alto",
      "all": [
        {
          "any": [
            { "is": { "loved": true } },
            { "gt": { "rating": 3 } }
          ]
        }
      ],
      "sort": "dateLoved",
      "order": "desc"
    }

  supermix.nsp: |
    {
      "name": "Super Mix",
      "comment": "Selección aleatoria de canciones con rating alto o que ya han sido reproducidas",
      "all": [
        {
          "any": [
            { "gt": { "rating": 3 } },
            { "gt": { "playCount": 0 } }
          ]
        }
      ],
      "sort": "random",
      "limit": 200
    }

  supersupermix.nsp: |
    {
      "name": "Super Super Mix",
      "comment": "Selección aleatoria de canciones con rating muy alto o reproducidas anteriormente",
      "all": [
        {
          "any": [
            { "gt": { "rating": 4 } },
            { "gt": { "playCount": 0 } }
          ]
        }
      ],
      "sort": "random",
      "limit": 200
    }
  
  top_60s.nsp: |
    {
      "name": "Top 60s Mix",
      "comment": "Canciones favoritas o reproducidas de los años 60",
      "all": [
        {
          "any": [
            { "is": { "loved": true } },
            { "gt": { "rating": 3 } },
            { "gt": { "playCount": 0 } }
          ]
        },
        { "inTheRange": { "year": [1961, 1970] } }
      ],
      "sort": "-rating,title",
      "limit": 25
    }

  top_70s.nsp: |
    {
      "name": "Top 70s Mix",
      "comment": "Canciones favoritas o reproducidas de los años 70",
      "all": [
        {
          "any": [
            { "is": { "loved": true } },
            { "gt": { "rating": 3 } },
            { "gt": { "playCount": 0 } }
          ]
        },
        { "inTheRange": { "year": [1971, 1980] } }
      ],
      "sort": "-rating,title",
      "limit": 25
    }

  top_80s.nsp: |
    {
      "name": "Top 80s Mix",
      "comment": "Canciones favoritas o reproducidas de los años 80",
      "all": [
        {
          "any": [
            { "is": { "loved": true } },
            { "gt": { "rating": 3 } },
            { "gt": { "playCount": 0 } }
          ]
        },
        { "inTheRange": { "year": [1981, 1990] } }
      ],
      "sort": "-rating,title",
      "limit": 25
    }

  top_90s.nsp: |
    {
      "name": "Top 90s Mix",
      "comment": "Canciones favoritas o reproducidas de los años 90",
      "all": [
        {
          "any": [
            { "is": { "loved": true } },
            { "gt": { "rating": 3 } },
            { "gt": { "playCount": 0 } }
          ]
        },
        { "inTheRange": { "year": [1991, 2000] } }
      ],
      "sort": "-rating,title",
      "limit": 25
    }

  top_00s.nsp: |
    {
      "name": "Top 00s Mix",
      "comment": "Canciones favoritas o reproducidas de los años 2000",
      "all": [
        {
          "any": [
            { "is": { "loved": true } },
            { "gt": { "rating": 3 } },
            { "gt": { "playCount": 0 } }
          ]
        },
        { "inTheRange": { "year": [2001, 2010] } }
      ],
      "sort": "-rating,title",
      "limit": 25
    }

