# find /mnt/music -type f -name "*.mp3" -exec bpm-tag -f {} \;
apiVersion: apps/v1
kind: Deployment
metadata:
  name: navidrome
  labels:
    app: navidrome
spec:
  replicas: 1
  selector:
    matchLabels:
      app: navidrome
      app.kubernetes.io/name: navidrome
  template:
    metadata:
      labels:
        app: navidrome
        app.kubernetes.io/name: navidrome
    spec:
      containers:
      - name: navidrome
        image: deluan/navidrome:latest
        ports:
        - containerPort: 4533
          name: http
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 1.5Gi
        envFrom:
          - configMapRef:
              name: navidrome-config
        env:
          - name: ND_LASTFM_APIKEY
            valueFrom:
              secretKeyRef:
                name: navidrome-lastfm-secret
                key: ND_LASTFM_APIKEY
          - name: ND_LASTFM_SECRET
            valueFrom:
              secretKeyRef:
                name: navidrome-lastfm-secret
                key: ND_LASTFM_SECRET
        securityContext:
          privileged: true
        volumeMounts:
        - name: dri
          mountPath: /dev/dri
          readOnly: false
        - name: cache
          mountPath: /data/cache
        - name: navidrome-data
          mountPath: /data
        - name: navidrome-backup
          mountPath: /backup
        - name: navidrome-music
          mountPath: /music
        - name: playlists
          mountPath: /music/playlists
      nodeSelector:
        kubernetes.io/hostname: caturra
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        # Group id (992) can be found running 
        # getent group render | cut -d: -f3
        supplementalGroups: [44, 107, 992]
      volumes:
      - name: dri
        hostPath:
          path: /dev/dri
      - name: cache
        emptyDir:
          medium: Memory
          sizeLimit: "1Gi"
      - name: navidrome-data
        hostPath:
          path: /mnt/navidrome
          type: DirectoryOrCreate
      - name: navidrome-backup
        hostPath:
          path: /mnt/navidrome/backup
          type: DirectoryOrCreate
      - name: navidrome-music
        hostPath:
          path: /mnt/music
          type: DirectoryOrCreate
      - name: playlists
        configMap:
          name: shared-playlists