apiVersion: v1
kind: PersistentVolume
metadata:
  name: navidrome-pv
spec:
  capacity:
    storage: "5Gi"
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/navidrome
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: navidrome-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "5Gi"
  storageClassName: ""
  volumeName: navidrome-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: music-pv
spec:
  capacity:
    storage: "120Gi"
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/music
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: music-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "120Gi"
  storageClassName: ""
  volumeName: music-pv