apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# https://github.com/buzzkit-dev/buzzkit
# https://github.com/buzzkit-dev/buzzkit/blob/main/docker-compose.yml
resources:
- deployment.yaml
- svc.yaml
- ingress.yaml

namespace: automation
