apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: buzzkit
  namespace: media
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: "web"
spec:
  ingressClassName: "traefik"
  rules:
    - host: buzzkit.lan
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: buzzkit
                port:
                  number: 2785