apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- sa.yaml
- config.yaml

# Database (WIP)
- database-pv.yaml
- database-deployment.yaml
- database-svc.yaml

# Cache
- cache-deployment.yaml
- cache-svc.yaml

# Server
- server-deployment.yaml
- server-svc.yaml
- server-ingress.yaml