apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- config.yaml

# Postgresql
- database-pv.yaml
- database-deployment.yaml
- database-svc.yaml

# VaultWarden
- server-deployment.yaml
- server-svc.yaml