apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: streaming

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: qbittorrent-jobs
  files:
  - scripts/common.sh
  - scripts/check-port-daemon.sh
  
- name: qbittorrent-scripts
  files:
  # Shared
  - scripts/common.sh

  # Init
  - scripts/01-setup-config.sh
  - scripts/check-port-daemon.sh

  # Torrent Hooks
  - scripts/torrent-added.sh
  - scripts/torrent-finished.sh
  - scripts/torrent-completed.sh

  # Pod Lifecycle
  - scripts/pod-post-start.sh
  - scripts/pod-pre-stop.sh

resources:
- cronjobs/check-port.yaml
- statefulset.yaml
- svc.yaml
- ingress.yaml