apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# Server
- home-assistant

# Addons
- frigate
- music-assistant
- mosquitto
- matter
- ring-mqtt
- eddie

# No devices
# - zwave 

namespace: home-assistant
