---
# Deployment de Wiki.js
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wikijs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wikijs
      app.kubernetes.io/name: wikijs
  template:
    metadata:
      labels:
        app: wikijs
        app.kubernetes.io/name: wikijs
    spec:
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: wikijs
        image: ghcr.io/requarks/wiki:latest
        env:
        - name: DB_TYPE
          value: "postgres"
        - name: DB_HOST
          value: "wikijs-postgresql"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "wiki"
        - name: DB_USER
          value: "wikijs"
        - name: DB_PASS
          value: "zABnbaudWjREtvqRNAHmDlOg"
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 25m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
          periodSeconds: 30
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3000
          periodSeconds: 15
          failureThreshold: 3
---
# PostgreSQL StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wikijs-postgresql
spec:
  serviceName: "wikijs-postgresql"
  replicas: 1
  selector:
    matchLabels:
      app: wikijs-postgresql
      app.kubernetes.io/name: wikijs-postgresql
  template:
    metadata:
      labels:
        app: wikijs-postgresql
        app.kubernetes.io/name: wikijs-postgresql
    spec:
      serviceAccountName: wikijs
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: postgresql
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "wiki"
        - name: POSTGRES_USER
          value: "wikijs"
        - name: POSTGRES_PASSWORD
          value: "zABnbaudWjREtvqRNAHmDlOg"
        resources:
          requests:
            cpu: 20m
            memory: 128Mi
        livenessProbe:
          exec:
            command: [ "pg_isready", "-U", "wikijs" ]
          initialDelaySeconds: 20
          periodSeconds: 30
          failureThreshold: 3
        readinessProbe:
          exec:
            command: [ "pg_isready", "-U", "wikijs" ]
          initialDelaySeconds: 10
          periodSeconds: 15
          failureThreshold: 3
        volumeMounts:
        - name: postgresql-data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: postgresql-data
      labels:
        app.kubernetes.io/name: wikijs-postgresql
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
---
# Services
apiVersion: v1
kind: Service
metadata:
  name: wikijs
  labels:
    app.kubernetes.io/name: wikijs
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: wikijs
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    nodePort: 30300
---
apiVersion: v1
kind: Service
metadata:
  name: wikijs-postgresql
  labels:
    app.kubernetes.io/name: wikijs-postgresql
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app.kubernetes.io/name: wikijs-postgresql
