apiVersion: batch/v1
kind: CronJob
metadata:
  name: transmission-port-syncer
  namespace: streaming
spec:
  schedule: "0 * * * *"
  concurrencyPolicy: Forbid
  suspend: true
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            vault.hashicorp.com/agent-inject: "true"
            vault.hashicorp.com/role: vault
            vault.hashicorp.com/agent-pre-populate-only : "true"
            vault.hashicorp.com/agent-inject-secret-transmission: "secret/data/transmission"
            vault.hashicorp.com/agent-inject-template-transmission: |
              {{- with secret "secret/data/transmission" -}}
              {{ .Data.data.USERNAME | writeToFile "/vault/secrets/user" "vault" "vault" "0640" }}
              {{ .Data.data.PASSWORD | writeToFile "/vault/secrets/password" "vault" "vault" "0640" }}
              {{- end -}}
        spec:
          restartPolicy: OnFailure
          containers:
          - name: transmission
            image: lscr.io/linuxserver/transmission:latest
            command: ["/bin/bash", "-c"]
            args:
              - |
                /scripts/check-port-daemon.sh
            env:
            - name: "FILE__USER"
              value: "/vault/secrets/user"
            - name: "FILE__PASS"
              value: "/vault/secrets/password"
            envFrom:
            - configMapRef:
                name: streaming-stack-config
            volumeMounts:
            - name: scripts
              mountPath: /scripts
            - name: config
              mountPath: /config
          nodeSelector:
            kubernetes.io/hostname: catuai
          tolerations:
          - key: node-role.kubernetes.io/control-plane
            operator: Exists
            effect: NoSchedule
          volumes:
          - name: scripts
            configMap:
              name: transmission-jobs
              defaultMode: 0755
          - name: config
            hostPath:
              path: /mnt/transmission
              type: DirectoryOrCreate