apiVersion: v1
kind: Service
metadata:
  name: pyload
spec:
  ports:
  - name: web
    protocol: TCP
    port: 8000
    targetPort: 8000
  - name: control
    protocol: TCP
    port: 7227
    targetPort: 7227
  - name: torrent
    port: 9666
    targetPort: 9666
  selector:
    app.kubernetes.io/name: pyload
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: pyload-lb
  annotations:
    external-dns.alpha.kubernetes.io/hostname: pyload.lan
spec:
  loadBalancerIP: 192.168.1.29
  type: LoadBalancer
  ports:
  - name: web
    protocol: TCP
    port: 80
    targetPort: 8000
  selector:
    app: pyload
