apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flaresolverr
spec:
  rules:
  - host: flaresolverr.citocafecito.work
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: flaresolverr
            port:
              number: 8191