apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: flaresolverr
spec:
  scaleTargetRef:
    name: flaresolverr
  minReplicaCount: 0
  maxReplicaCount: 6
  cooldownPeriod: 300
  triggers:
  - type: cpu
    metricType: Utilization
    metadata:
      value: "70"
