apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: flaresolverr
spec:
  hosts:
  - flaresolverr.citocafecito.work
  targetPendingRequests: 1
  scaleTargetRef:
    name: flaresolverr
    service: flaresolverr
    port: 8191
  replicas:
    min: 0
    max: 4