apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: flaresolverr
spec:
  scaleTargetRef:
    name: flaresolverr
    service: flaresolverr
    port: 8191
  replicas:
    min: 0
    max: 4
  scaledownPeriod: 300
