apiVersion: v1
kind: Service
metadata:
  name: garage-bridge
  namespace: media
spec:
  type: ExternalName
  externalName: garage.storage.svc.cluster.local
  ports:
  - port: 3902
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: puppysignal
  annotations:
    cloudflare-tunnel.ingress.kubernetes.io/backend-protocol: "http"
spec:
  ingressClassName: cloudflare-tunnel
  rules:
  - host: puppysignal.citocafecito.work
    http:
      paths:
        - path: /api
          pathType: Prefix
          backend:
            service:
              name: puppysignal-backend
              port:
                number: 8000
        - path: /
          pathType: Prefix
          backend:
            service:
              name: garage-bridge
              port:
                number: 3902