apiVersion: v1
kind: PersistentVolume
metadata:
  name: puppysignal-pv
spec:
  capacity:
    storage: "1Gi"
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/puppysignal
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: puppysignal-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "1Gi"
  volumeName: puppysignal-pv
  storageClassName: ""