apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-dns-shared-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-dns-shared-role
subjects:
- kind: ServiceAccount
  name: external-dns
  namespace: core
- kind: ServiceAccount
  name: external-dns
  namespace: networking