apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: external-dns
  template:
    metadata:
      labels:
        app: external-dns
      annotations:
        app.kubernetes.io/documentation: "https://github.com/kubernetes-sigs/external-dns/blob/master/docs/tutorials/pihole.md"
    spec:
      serviceAccountName: external-dns
      containers:
      - name: external-dns
        image: registry.k8s.io/external-dns/external-dns:v0.20.0
        args:
          - --source=service
          - --source=ingress
          - --registry=noop
          - --domain-filter=lan
          - --policy=upsert-only
          - --provider=pihole
        env:
        - name:  EXTERNAL_DNS_PIHOLE_SERVER
          value: "http://192.168.1.10"
        - name: EXTERNAL_DNS_PIHOLE_API_VERSION
          value: "6"
        - name: EXTERNAL_DNS_PIHOLE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pihole-secret
              key: WEBPASSWORD
        resources:
          requests:
            cpu: 5m
            memory: 32Mi
          limits:
            cpu: 50m
            memory: 100Mi
      securityContext:
        fsGroup: 65534
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"