apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: external-dns
  template:
    metadata:
      labels:
        app: external-dns
      annotations:
        app.kubernetes.io/documentation: "https://github.com/kubernetes-sigs/external-dns/blob/master/docs/tutorials/pihole.md"
    spec:
      serviceAccountName: external-dns
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - external-dns-cloudflare
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: external-dns
        image: registry.k8s.io/external-dns/external-dns:v0.20.0
        args:
          - --source=service
          - --source=ingress
          - --domain-filter=lan
          - --policy=upsert-only
          - --provider=pihole
        env:
        - name:  EXTERNAL_DNS_PIHOLE_SERVER
          value: "http://pihole.networking.svc.cluster.local"
        - name: EXTERNAL_DNS_PIHOLE_API_VERSION
          value: "6"
        - name: EXTERNAL_DNS_PIHOLE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pihole-secret
              key: WEBPASSWORD
      securityContext:
        fsGroup: 65534
      nodeSelector:
        kubernetes.io/hostname: catuai
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"