apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# Not enough cpu available
# - mydrive
# - reactive-resume
# - unmanic (no enable till i get a new GPU)
- infisical
- pyload

# Work in progress. Stoped due no enough hardware
# - next-cloud
- garage

# Deprecated
# - jdownloader

namespace: storage
