apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: garage-ingress
spec:
  rules:
  - host: s3.garage.lan
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: garage
            port:
              number: 3900
  - host: admin.garage.lan
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: garage
            port:
              number: 3903
  - host: garage.lan
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: garage-webui
            port:
              number: 3909