apiVersion: apps/v1
kind: Deployment
metadata:
  name: garage
  labels:
    app: garage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: garage
  template:
    metadata:
      labels:
        app: garage
    spec:
      containers:
      - name: garage
        image: dxflrs/garage:v2.2.0
        imagePullPolicy: IfNotPresent
        ports:
        - name: s3
          containerPort: 3900
        - name: rpc
          containerPort: 3901
        - name: s3web
          containerPort: 3902
        - name: api
          containerPort: 3903
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
          limits:
            cpu: 200m
            memory: 128Mi
        volumeMounts:
        - name: config-volume
          mountPath: /etc/garage.toml
          subPath: garage.toml
        - name: meta
          mountPath: /var/lib/garage/meta
        - name: data
          mountPath: /var/lib/garage/data
      nodeSelector:
        kubernetes.io/hostname: catuai
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      volumes:
      - name: config-volume
        configMap:
          name: garage-config
      - name: meta
        hostPath:
          path: /mnt/garage/meta
      - name: data
        hostPath:
          path: /mnt/garage/data
