kind: Service
apiVersion: v1
metadata:
  name: garage
  # annotations:
  #   metallb.universe.tf/allow-shared-ip: "garage-cluster-ip"
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.34
  selector:
    app: garage
  ports:
  - name: s3
    protocol: TCP
    port: 3900
    targetPort: 3900
  - name: admin-api
    protocol: TCP
    port: 3903
    targetPort: 3903
