apiVersion: apps/v1
kind: Deployment
metadata:
  name: garage-webui
  labels:
    app: garage-webui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: garage-webui
  template:
    metadata:
      labels:
        app: garage-webui
    spec:
      containers:
      - name: garage-webui
        image: khairul169/garage-webui:latest
        ports:
        - containerPort: 3000
        env:
        - name: GARAGE_ADMIN_URL
          value: "http://garage:3903"
        - name: GARAGE_ADMIN_TOKEN
          value: "141113" 
        - name: GARAGE_S3_REGION
          value: "garage"
        - name: GARAGE_S3_ENDPOINT
          value: "http://garage:3900"
        resources:
          requests:
            cpu: 50m
            memory: 32Mi
          limits:
            cpu: 100m
            memory: 64Mi
        volumeMounts:
        - name: config-volume
          mountPath: /etc/garage.toml
          subPath: garage.toml
      nodeSelector:
        kubernetes.io/hostname: catuai
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      volumes:
      - name: config-volume
        configMap:
          name: garage-config