apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- cloudflared
- vault
# - lightpanda (Done, but not in use)
# - ntf (Working progress)
# - whisper-asr
# Deprecated
# - chromium

namespace: core
