apiVersion: v1
kind: PersistentVolume
metadata:
  name: dispatcharr-pv
spec:
  capacity:
    storage: "1Gi"
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/dispatcharr
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dispatcharr-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "1Gi"
  volumeName: dispatcharr-pv
  storageClassName: ""