apiVersion: v1
kind: Service
metadata:
  name: dispatcharr
  labels:
    app: dispatcharr
    app.kubernetes.io/name: dispatcharr
    app.kubernetes.io/instance: streaming-stack
    app.kubernetes.io/part-of: streaming-stack
spec:
  selector:
    app: dispatcharr
    app.kubernetes.io/name: dispatcharr
    app.kubernetes.io/instance: streaming-stack
  ports:
  - name: web
    port: 9191
    targetPort: 9191
  - name: tcp
    port: 5656
    targetPort: 5656
  - name: celery
    port: 8001
    targetPort: 8001