apiVersion: apps/v1
kind: Deployment
metadata:
  name: lidify
  labels:
    app: lidify
spec:
  replicas: 0
  selector:
    matchLabels:
      app: lidify
  template:
    metadata:
      labels:
        app: lidify
    spec:
      containers:
        - name: lidify
          image: thewicklowwolf/lidify:latest
          ports:
            - containerPort: 5000
          env:
            - name: mode
              value: "LastFM"
            - name: auto_start
              value: "True"
            - name: lidarr_address
              value: http://lidarr.streaming.svc.cluster.local:8989
            - name: last_fm_api_key
              valueFrom:
                secretKeyRef:
                  name: navidrome-lastfm-secret
                  key: ND_LASTFM_APIKEY
            - name: last_fm_api_secret
              valueFrom:
                secretKeyRef:
                  name: navidrome-lastfm-secret
                  key: ND_LASTFM_SECRET
            - name: lidarr_api_key
              valueFrom:
                secretKeyRef:
                  name: lidarr-secret
                  key: LIDARR_API_KEY
          volumeMounts:
            - name: lidify-config
              mountPath: /lidify/config
            - name: localtime
              mountPath: /etc/localtime
              readOnly: true
            - name: music 
              mountPath: /data/media/music/
          resources:
            requests:
              cpu: "25m"
              memory: "32Mi"
            limits:
              cpu: "150m"
              memory: "128Mi"
      nodeSelector:
        kubernetes.io/hostname: catuai
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      volumes:
        - name: lidify-config
          hostPath:
            path: /mnt/lidify
            type: DirectoryOrCreate
        - name: localtime
          hostPath:
            path: /etc/localtime
            type: File
        - name: music
          hostPath:
            path: /mnt/multimedia/music
          