apiVersion: v1
kind: Service
metadata:
  name: nextcloud
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: nextcloud
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30801
