apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # CNI
  - https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml

  # Cert Manager
  - https://github.com/cert-manager/cert-manager/releases/download/v1.21.2/cert-manager.yaml

  # Kube System (Not Ready)
  # - kube-system 

  # Aplicaciones y stacks del cluster
  - metallb
  - actions
  - networking
  - core
  - automation
  - auth
  - home-assistant
  - storage
  - media
  - monitoring
  - streaming