apiVersion: v1
kind: Namespace
metadata:
  name: puppysignal-development
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: puppysignal-mongodb-dev
  namespace: puppysignal-development
spec:
  serviceName: puppysignal-mongodb-dev
  replicas: 1
  selector:
    matchLabels:
      app: puppysignal-mongodb-dev
      app.kubernetes.io/name: puppysignal-mongodb-dev
      app.kubernetes.io/part-of: puppysignal-dev
  template:
    metadata:
      labels:
        app: puppysignal-mongodb-dev
        app.kubernetes.io/name: puppysignal-mongodb-dev
        app.kubernetes.io/part-of: puppysignal-dev
    spec:
      containers:
        - name: mongo
          image: mongo:8.2.3
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: admin
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: admin
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: data
              mountPath: /data/db
          readinessProbe:
            exec:
              command: ["mongosh", "--eval", "db.adminCommand('ping')"]
            initialDelaySeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            exec:
              command: ["mongosh", "--eval", "db.adminCommand('ping')"]
            initialDelaySeconds: 30
            timeoutSeconds: 5
      nodeSelector:
        kubernetes.io/hostname: catuai
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      volumes:
        - name: data
          hostPath:
            path: /mnt/puppysignal-mongodb-dev
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: puppysignal-mongodb-dev
  namespace: puppysignal-development
  annotations:
    metallb.universe.tf/loadBalancerIPs: "192.168.1.19"
  labels:
    app: puppysignal-mongodb-dev
    app.kubernetes.io/name: puppysignal-mongodb-dev
    app.kubernetes.io/part-of: puppysignal-dev
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.30
  selector:
    app: puppysignal-mongodb-dev
    app.kubernetes.io/name: puppysignal-mongodb-dev
    app.kubernetes.io/part-of: puppysignal-dev
  ports:
    - name: mongodb
      port: 27017
      targetPort: 27017
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: puppysignal-mongodb-dev
#   namespace: puppysignal-development
# spec:
#   ingressClassName: traefik
#   rules:
#   - host: mongodb.puppysignal.dev.lan
#     http:
#       paths:
#         - path: /
#           pathType: Prefix
#           backend:
#             service:
#               name: puppysignal-mongodb-dev
#               port:
#                 number: 27017
# ---
# apiVersion: traefik.io/v1alpha1
# kind: IngressRouteTCP
# metadata:
#   name: puppysignal-mongodb-dev
#   namespace: puppysignal-development
# spec:
#   entryPoints:
#     - mongo # Nombre del entryPoint TCP en Traefik escuchando en el puerto 27017
#   routes:
#     - match: HostSNI(`*`)
#       services:
#         - name: puppysignal-mongodb-dev
#           port: 27017