apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: k8s-runners
  namespace: actions
spec:
  selector:
    matchLabels:
      app: k8s-runners
      app.kubernetes.io/name: k8s-runners
  template:
    metadata:
      labels:
        app: k8s-runners
        app.kubernetes.io/name: k8s-runners
    spec:
      dockerEnabled: false
      ephemeral: true
      organization: citocafecito-homelab
      serviceAccountName: github-runner
      labels:
      - arc
      - k8s
      env: []
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: k8s-runner-autoscaler
  namespace: actions
spec:
  scaleTargetRef:
    kind: RunnerDeployment
    name: k8s-runners
  minReplicas: 0
  maxReplicas: 5
  scaleDownDelaySecondsAfterScaleOut: 300
  metrics:
  - type: TotalNumberOfQueuedAndInProgressWorkflowRuns
    repositoryNames:
    - ansible-cafeteria
    - k8s-gitops
    - habiflix-ux
