apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole-primary
  namespace: networking
  labels:
    app: pihole
    instance: primary
    app.kubernetes.io/name: pihole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pihole
      instance: primary
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: pihole
        instance: primary
        app.kubernetes.io/name: pihole
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "vault"
        vault.hashicorp.com/agent-inject-secret-admin_password: "secret/data/pihole"
        vault.hashicorp.com/agent-inject-template-admin_password: |
          {{- with secret "secret/data/pihole" -}}
          {{ .Data.data.WEBPASSWORD }}
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-api_key: "secret/data/pihole"
        vault.hashicorp.com/agent-inject-template-api_key: |
          {{- with secret "secret/data/pihole" -}}
          {{ .Data.data.API_KEY }}
          {{- end }}
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      terminationGracePeriodSeconds: 10
      containers:
      - name: pihole
        image: pihole/pihole:latest
        envFrom:
        - configMapRef:
            name: pihole-global
        - configMapRef:
            name: pihole-primary
        ports:
        - name: dhcp
          containerPort: 67
          protocol: UDP
        - name: dns-tcp
          containerPort: 53
          protocol: TCP
        - name: dns-udp
          containerPort: 53
          protocol: UDP
        - name: dhcp
          containerPort: 67
          protocol: UDP
        - name: dhcpv6
          containerPort: 547
          protocol: UDP
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 256Mi
        securityContext:
          capabilities:
            add:
            - CHOWN
            - NET_ADMIN
            - NET_BIND_SERVICE
            - NET_RAW
            - SYS_NICE
            - SYS_TIME
        volumeMounts:
        - name: pihole-etc
          mountPath: /etc/pihole
        - name: shm-volume
          mountPath: /dev/shm
        - name: custom-dns
          mountPath: /etc/dnsmasq.d/custom.conf
          subPath: custom.conf
        - name: adlists
          mountPath: /etc/pihole/adlists.list
          subPath: adlists.list
      nodeSelector:
        kubernetes.io/hostname: catuai
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      volumes:
      - name: shm-volume
        emptyDir:
          medium: Memory
          sizeLimit: 256Mi
      - name: custom-dns
        configMap:
          name: pihole-custom-dns
      - name: adlists
        configMap:
          name: pihole-adlists
      - name: pihole-etc
        hostPath:
          path: /mnt/pihole
          type: DirectoryOrCreate