apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
      app.kubernetes.io/name: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
        app.kubernetes.io/name: mosquitto
    spec:
      containers:
      - name: mosquitto
        image: eclipse-mosquitto
        env:
        - name: TZ
          value: "America/Bogota"
        ports:
        - containerPort: 1883
        - containerPort: 9001
        resources:
          requests:
            cpu: 1m
            memory: 64Mi
          limits:
            cpu: 10m
            memory: 128Mi
        securityContext:
          privileged: true
        volumeMounts:
        - name: config
          mountPath: /mosquitto/config
          readOnly: false
      volumes:
      - name: config
        configMap:
          name: mosquitto-config