apiVersion: v1
kind: ConfigMap
metadata:
  name: streaming-stack-config
data:
  PUID: "1000"
  PGID: "1000"
  TZ: "America/Bogota"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vpn-config
data:
  FIREWALL_INPUT_PORTS: "8080"
  FIREWALL_OUTBOUND_SUBNETS: "192.168.1.0/24,10.244.0.0/16,10.96.0.0/12"
  VPN_SERVICE_PROVIDER: "private internet access"
  VPN_TYPE: "openvpn"
  OPENVPN_PROTOCOL: "udp"
  PRIVATE_INTERNET_ACCESS_OPENVPN_ENCRYPTION_PRESET: "normal"
  SERVER_REGIONS: "Colombia,Brazil,Panama,Netherlands,CA Montreal"

  # https://github.com/qdm12/gluetun-wiki/blob/main/setup/advanced/vpn-port-forwarding.md
  PORT_FORWARD_ONLY: "true"
  VPN_PORT_FORWARDING: "on"
  VPN_PORT_FORWARDING_UP_COMMAND: "/bin/sh /scripts/update-port.sh {{PORT}}"
  VPN_PORT_FORWARDING_STATUS_FILE: "/config/forwarded_port"