apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: streaming

components:
  - ../../components/scripts

resources:
- config.yaml
- pvc.yaml

# Downloaders
- qbittorrent
- transmission

## Arr* arrs
- prowlarr
- sonarr
- radarr
- bazarr
- lidarr
- seerr

# Habiflix Stack
- dispatcharr
- jellystat
- jellyfin
# - plex # (deprecated)
# - stremio # (Not ready yet)