apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: streaming

resources:
## Base
- ../shared-playlists
- config.yaml
- pvc.yaml

## Apps
# - apps/nzbget.yaml
- apps/transmission.yaml
# - apps/deluge.yaml
# - apps/qbittorrent.yaml (deprecated)
- apps/prowlarr.yaml
- apps/sonarr.yaml
- apps/radarr.yaml
- apps/bazarr.yaml
- apps/lidarr.yaml
- apps/jellyserr.yaml
- apps/plex.yaml
# Not enough resources / uncompleted tests
# - apps/tinymediamanager.yaml
# - apps/tdarr.yaml
# - apps/autobrr.yaml

## Complex apps
- dispatcharr
- jellyfinn

## Jobs
- jobs/split2flac.yaml