apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: streaming

resources:
## Base
- ../shared-playlists
- config.yaml
- pvc.yaml
- ingress.yaml

## Apps
- apps/transmission.yaml
# - apps/autobrr.yaml
# - apps/qbittorrent.yaml
- apps/flaresolverr.yaml
- apps/prowlarr.yaml
- apps/sonarr.yaml
- apps/radarr.yaml
- apps/bazarr.yaml
- apps/lidarr.yaml
- apps/dispatcharr.yaml
- apps/jellyserr.yaml
- apps/jellyfin.yaml
- apps/plex.yaml
# Not enough resources
# - apps/tinymediamanager.yaml
# - apps/tdarr.yaml

## Jobs
- jobs/split2flac.yaml