apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# - proxy.yaml

# Apps
- dashboard
- wiki
- suwayomi
- linkstack
- navidrome
# - lidify
# - excalidraw
- flaresolverr

namespace: media
