apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true
  
configMapGenerator:
#   - name: matter-bridge-config
#     files:
#       - files/matterbridge.toml

resources:
# Server
- server-pvc.yaml
- server-deployment.yaml
- server-svc.yaml

# Bridge (deprecated needs a Home Assistant Matter Hub)
# - bridge-deployment.yaml

# Matter Hub (deprecated needs a Home Assistant Matter Hub)
# https://github.com/RiDDiX/home-assistant-matter-hub/
# - hub-deployment.yaml
# - hub-svc.yaml
# - hub-ingress.yaml

namespace: home-assistant

labels:
  - pairs:
      app.kubernetes.io/part-of: matter-thread
    includeSelectors: true