apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true
  
configMapGenerator:
#   - name: mosquitto-config
#     files:
#       - files/matterbridge.toml

resources:
# Server
- server-pvc.yaml
- server-deployment.yaml
- server-svc.yaml

# Bridge (deprecated)
# - bridge-deployment.yaml

namespace: home-assistant

labels:
  - pairs:
      app.kubernetes.io/part-of: matter-thread
    includeSelectors: true