apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns-cloudflare
  namespace: core
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: external-dns-cloudflare
  template:
    metadata:
      labels:
        app: external-dns-cloudflare
    spec:
      serviceAccountName: external-dns
      containers:
      - name: external-dns
        image: registry.k8s.io/external-dns/external-dns:v0.20.0
        args:
          - --source=service
          - --source=ingress
          - --provider=cloudflare
          - --domain-filter=citocafecito.work
          # - --cloudflare-dns-records-proxied
          - --cloudflare-proxied
          - --txt-owner-id=k8s-cluster
          - --log-level=info
        env:
        - name: CF_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: cloudflared-secret
              key: token
        - name: CF_API_EMAIL
          valueFrom:
            secretKeyRef:
              name: cloudflared-secret
              key: email
      securityContext:
        fsGroup: 65534
      nodeSelector:
        kubernetes.io/hostname: catuai
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"