apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns-cloudflare
  namespace: core
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: external-dns-cloudflare
  template:
    metadata:
      labels:
        app: external-dns-cloudflare
    spec:
      serviceAccountName: cloudflared
      containers:
      - name: external-dns
        image: registry.k8s.io/external-dns/external-dns:v0.20.0
        args:
          - --source=service
          - --source=ingress
          - --provider=cloudflare
          - --domain-filter=citocafecito.work
          - --cloudflare-proxied
          - --policy=sync
          - --cloudflare-record-comment="provisioned by citocafecito k8s cluster"
          - --txt-owner-id=citocafecito-homelab
        env:
        - name: CF_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: cloudflare-api
              key: api-token
        resources:
          requests:
            cpu: 5m
            memory: 32Mi
          limits:
            cpu: 50m
            memory: 100Mi
      securityContext:
        fsGroup: 65534