apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns-cloudflare
  namespace: core
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: external-dns-cloudflare
  template:
    metadata:
      labels:
        app: external-dns-cloudflare
    spec:
      serviceAccountName: cloudflared
      containers:
      - name: external-dns
        image: registry.k8s.io/external-dns/external-dns:v0.20.0
        args:
          - --source=service
          - --source=ingress
          - --provider=cloudflare
          - --domain-filter=citocafecito.work
          - --cloudflare-proxied
          - --annotation-filter=external-dns.alpha.kubernetes.io/hostname
          - --cloudflare-record-comment="provisioned by citocafecito k8s cluster"
        env:
        - name: CF_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: cloudflared-secret
              key: api
      securityContext:
        fsGroup: 65534
      nodeSelector:
        kubernetes.io/hostname: castillo
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"