apiVersion: apps/v1
kind: Deployment
metadata:
  name: frigate
  namespace: home-assistant
  labels:
    app: frigate
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: frigate
  template:
    metadata:
      labels:
        app: frigate
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "vault"
        vault.hashicorp.com/agent-extra-secret: "frigate-templates"
        vault.hashicorp.com/agent-inject-secret-config.yml: "secret/data/frigate"
        vault.hashicorp.com/agent-inject-template-file-config.yml: "/vault/custom/config.yml.tpl"
    spec:
      serviceAccountName: frigate
      automountServiceAccountToken: true
      containers:
      - name: frigate
        image: ghcr.io/blakeblackshear/frigate:stable-rocm
        imagePullPolicy: IfNotPresent
        command:
        - /bin/bash
        - -c
        - |
          mkdir -p /config
          cp /vault/secrets/config.yml /config/config.yml
          exec /init
        env:
        - name: TZ
          value: "America/Bogota"
        - name: LIBVA_DRIVER_NAME
          value: "radeonsi"
        resources:
          limits:
            cpu: "2"
            memory: 2Gi
          requests:
            cpu: "500m"
            memory: 1Gi
        ports:
        - name: http
          containerPort: 5000
        - name: rtsp
          containerPort: 8554
        - name: go2rtc
          containerPort: 1984
        - name: https-ui
          containerPort: 8971
        - name: webrtc-tcp
          containerPort: 8555
        - name: webrtc-udp
          containerPort: 8555
          protocol: UDP
        securityContext:
          privileged: true
          capabilities:
            drop:
            - ALL
            add:
            - CAP_PERFMON
            - CHOWN
            - DAC_OVERRIDE
            - FOWNER
            - SETGID
            - SETUID
            - SYS_ADMIN
        volumeMounts:
        - name: dshm
          mountPath: /dev/shm
        - name: cache
          mountPath: /tmp/cache
        - name: dri 
          mountPath: /dev/dri
          readOnly: false
        - name: media
          mountPath: /media/frigate
        - name: localtime
          mountPath: /etc/localtime
          readOnly: true
        - name: timezone
          mountPath: /etc/timezone
          readOnly: true
      nodeSelector:
        kubernetes.io/hostname: catimore
      securityContext:
        runAsUser: 0
        runAsNonRoot: false
        fsGroup: 107
        supplementalGroups: [44, 104, 107, 992]
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
          sizeLimit: 512Mi
      - name: cache
        emptyDir:
          medium: Memory
          sizeLimit: 1Gi
      - name: dri
        hostPath:
          path: /dev/dri
      - name: localtime
        hostPath:
          path: /etc/localtime
          type: File
      - name: timezone
        hostPath:
          path: /etc/timezone
          type: FileOrCreate
      - name: media
        emptyDir: {}