homeassistant:
  name: !secret ha_name
  latitude: !secret ha_latitude
  longitude: !secret ha_longitude
  elevation: !secret ha_elevation
  unit_system: metric
  time_zone: America/Bogota
  packages: !include_dir_named packages

allowlist_external_dirs:
  - "/config/www/camaras"
  - "/config/www/records"
  - "/config/www/timbre"
  - "/config/www/snapshots"

media_dirs:
  audios: /config/www/audios
  camaras: /config/www/camaras
  records: /config/www/records
  snapshots: /config/www/snapshots
  timbre: /config/www/timbre

default_config:

prometheus:

wake_on_lan:

api:

logger:
  default: warning
  logs:
    custom_components.stellantis_vehicles: debug

frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml