ingress:
  mass: # Funciona perfectamente
    title: "Music Assistant"
    icon: "mdi:music"
    url: "http://music-assistant.home-assistant.svc.cluster.local:8095"
    ui_mode: toolbar
    work_mode: ingress
    headers:
      # Pasa el usuario logueado en Home Assistant a la cabecera de la app
      Remote-User: $username

  ## Kite (K8s)
  kite:
    title: "Kite (K8s)"
    icon: "mdi:kubernetes"
    index: /
    url: "http://kite.monitoring.svc.cluster.local:8080"
    ui_mode: toolbar
    work_mode: ingress
    rewrite:
      - mode: body
        match: /(assets|static|api)/
        replace: $http_x_ingress_path/\1/
      - mode: body
        match: \\/(assets|static|api)\\/
        replace: $http_x_ingress_path\/\1\/
      - mode: header
        name: "(Location|Set-Cookie)"
        match: /(assets|static|api)/
        replace: $http_x_ingress_path/\1/

  # habiflix: # No funciona
  #   title: "Habiflix Stats"
  #   icon: "mdi:movie"
  #   url: "http://jellystat.streaming.svc.cluster.local:3000"
  #   work_mode: ingress

  # filescastillo: # No funciona
  #   title: "Castillo Explorer"
  #   icon: "mdi:movie"
  #   url: "http://192.168.1.12:9000"
  #   work_mode: ingress