shell_command:
  limpiar_timbre: "find /config/www/timbre/{thumbs,videos} -type f -mtime +7 -delete"
  limpiar_capturas: "find /config/www/snapshots -type f -mtime +7 -delete"
  limpiar_grabaciones: "find /config/www/records -type f -mtime +30 -delete"