apiVersion: apps/v1
kind: Deployment
metadata:
  name: suwayomi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: suwayomi
      app.kubernetes.io/name: suwayomi
  template:
    metadata:
      labels:
        app: suwayomi
        app.kubernetes.io/name: suwayomi
        tier: disposable
      annotations:
        app.kubernetes.io/documentation: "https://github.com/Suwayomi/Suwayomi-Server-docker/pkgs/container/tachidesk"
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: vault
        vault.hashicorp.com/agent-inject-secret-suwayomi: "secret/data/suwayomi"
        vault.hashicorp.com/agent-inject-template-suwayomi: |
          {{- with secret "secret/data/suwayomi" -}}
          {{ .Data.data.USERNAME | writeToFile "/vault/secrets/AUTH_USERNAME" "vault" "vault" "0644" }}
          {{ .Data.data.PASSWORD | writeToFile "/vault/secrets/AUTH_PASSWORD" "vault" "vault" "0644" }}
          {{- end -}}
    spec:
      automountServiceAccountToken: true
      containers:
      - name: suwayomi
        image: ghcr.io/suwayomi/suwayomi-server:preview
        ports:
        - containerPort: 4567
        - containerPort: 8181
        envFrom:
        - configMapRef:
            name: suwayomi-config
        resources:
          requests:
            cpu: "100m"
            memory: "1Gi"
          limits:
            cpu: "500m"
            memory: "2Gi"
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: suwayomi-storage
          mountPath: /home/suwayomi/.local/share/Tachidesk/downloads
          subPath: downloads
        - name: suwayomi-storage
          mountPath: /home/suwayomi/.local/share/Tachidesk/extensions
          subPath: extensions
        - name: suwayomi-storage
          mountPath: /home/suwayomi/.local/share/Tachidesk/backups
          subPath: backups
        - name: suwayomi-storage
          mountPath: /home/suwayomi/.local/share/Tachidesk/local
          subPath: local
        - name: suwayomi-storage
          mountPath: /home/suwayomi/.local/share/Tachidesk/settings
          subPath: settings
        - name: suwayomi-cache
          mountPath: /home/suwayomi/.local/share/Tachidesk/cache
      nodeSelector:
        kubernetes.io/hostname: castillo
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
      volumes:
      - name: suwayomi-storage
        persistentVolumeClaim:
          claimName: suwayomi-pvc
      - name: suwayomi-cache
        emptyDir:
          medium: Memory 
          sizeLimit: "256Mi"
