apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: eddie

resources:
# Eddie's Voice
- kokoro-deployment.yaml
- kokoro-svc.yaml
- wyoming-deployment.yaml
- wyoming-svc.yaml

# Eddie's Mind

# Eddie's Eyes

labels:
  - pairs:
      app.kubernetes.io/part-of: eddie-voice-assistant
      tier: disposable
    includeSelectors: true