apiVersion: apps/v1
kind: Deployment
metadata:
  name: transmission
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: transmission
      app.kubernetes.io/name: transmission
  template:
    metadata:
      labels:
        app: transmission
        app.kubernetes.io/name: transmission
        app.kubernetes.io/part-of: streaming-stack
      annotations:
        app.kubernetes.io/documentation: "https://docs.linuxserver.io/images/docker-transmission/"
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-init-first: "true"
        #
        ## --- Transmission
        #
        vault.hashicorp.com/role: vault
        vault.hashicorp.com/agent-inject-secret-transmission: "secret/data/transmission"
        vault.hashicorp.com/agent-inject-template-transmission: |
          {{- with secret "secret/data/transmission" -}}
          {{ .Data.data.USERNAME | writeToFile "/vault/secrets/user" "vault" "vault" "0640" }}
          {{ .Data.data.PASSWORD | writeToFile "/vault/secrets/password" "vault" "vault" "0640" }}
          {{- end -}}
        # #
        # ## --- PIA VPN
        # #
        # vault.hashicorp.com/agent-inject-secret-vpn: "secret/data/pia"
        # vault.hashicorp.com/agent-inject-template-vpn: |
        #   {{- with secret "secret/data/pia" -}}
        #   {{ .Data.data.username | writeToFile "/vault/secrets/vpn_user" "vault" "vault" "0640" }}
        #   {{ .Data.data.password | writeToFile "/vault/secrets/vpn_pass" "vault" "vault" "0640" }}
        #   {{- end -}}
    spec:
      dnsPolicy: ClusterFirst
      containers:
      - name: transmission
        image: lscr.io/linuxserver/transmission:latest
        ports:
        - containerPort: 9091
          name: webui
          protocol: TCP
        env:
          - name: "FILE__USER"
            value: "/vault/secrets/user"
          - name: "FILE__PASS"
            value: "/vault/secrets/password"
          # Base Config
          - name: TRANSMISSION_DOWNLOAD_DIR
            value: "/downloads"
          # Automation
          - name: TRANSMISSION_SCRIPT_TORRENT_ADDED_ENABLED
            value: "true"
          - name: TRANSMISSION_SCRIPT_TORRENT_ADDED_FILENAME
            value: "/scripts/added.sh"
          - name: TRANSMISSION_SCRIPT_TORRENT_DONE_ENABLED
            value: "true"
          - name: TRANSMISSION_SCRIPT_TORRENT_DONE_FILENAME
            value: "/scripts/finished.sh"
          - name: TRANSMISSION_SCRIPT_TORRENT_DONE_SEEDING_ENABLED
            value: "true"
          - name: TRANSMISSION_SCRIPT_TORRENT_DONE_SEEDING_FILENAME
            value: "/scripts/completed.sh"
          # Ratios & Queue
          - name: TRANSMISSION_INCOMPLETE_DIR_ENABLED
            value: "false"
          - name: TRANSMISSION_RENAME_PARTIAL_FILES
            value: "false"
          - name: TRANSMISSION_RATIO_LIMIT
            value: "3.0"
          - name: TRANSMISSION_RATIO_LIMIT_ENABLED
            value: "true"
          - name: TRANSMISSION_DOWNLOAD_QUEUE_ENABLED
            value: "false"
          - name: TRANSMISSION_SEED_QUEUE_ENABLED
            value: "false"
          - name: TRANSMISSION_DOWNLOAD_QUEUE_SIZE
            value: "999"
          - name: TRANSMISSION_SEED_QUEUE_SIZE
            value: "999"
          # Networking
          - name: TRANSMISSION_PEER_PORT_RANDOM_ON_START
            value: "true"
          - name: TRANSMISSION_PEER_LIMIT_PER_TORRENT
            value: "20"
        envFrom:
        - configMapRef:
            name: streaming-stack-config
        resources:
          requests:
            cpu: 50m
            memory: 256Mi
          limits:
            cpu: 250m
            memory: 1Gi
        volumeMounts:
        - name: scripts
          mountPath: /custom-cont-init.d/01-setup-config.sh
          subPath: 01-setup-config.sh
        - name: scripts
          mountPath: /scripts
        - name: config
          mountPath: /config/torrents
          subPath: torrents
        - name: config
          mountPath: /config/resume
          subPath: resume
        - name: config
          mountPath: /config/watch
          subPath: watch
        - name: config
          mountPath: /config/pending_tags.txt
          subPath: pending_tags.txt
        - name: config
          mountPath: /config/queue.json
          subPath: queue.json
        - name: config
          mountPath: /watch
          subPath: watch
        - name: downloads
          mountPath: /downloads
      # - name: vpn
      #   image: qmcgaw/gluetun:latest
      #   ports:
      #   - containerPort: 8000
      #     name: api
      #     protocol: TCP
      #   - containerPort: 9091
      #     name: webui
      #     protocol: TCP
      #   securityContext:
      #     capabilities:
      #       add: ["NET_ADMIN"]
      #   env:
      #   - name: FIREWALL_INPUT_PORTS
      #     value: "9091"
      #   - name: FIREWALL_OUTBOUND_SUBNETS
      #     value: "192.168.1.0/24,10.244.0.0/16,10.96.0.0/12"
        
      #   # --- Open VPN
      #   - name: OPENVPN_USER_SECRETFILE
      #     value: "/vault/secrets/vpn_user"
      #   - name: OPENVPN_PASSWORD_SECRETFILE
      #     value: "/vault/secrets/vpn_pass"
      #   - name: OPENVPN_PROTOCOL
      #     value: "udp"
        
      #   # --- PIA
      #   - name: PRIVATE_INTERNET_ACCESS_OPENVPN_ENCRYPTION_PRESET
      #     value: "normal"
        
      #   # --- Gluetun Configuration
      #   - name: VPN_TYPE
      #     value: "openvpn"
      #   - name: PORT_FORWARD_ONLY
      #     value: "true"
      #   - name: VPN_PORT_FORWARDING
      #     value: "on"
      #   - name: VPN_PORT_FORWARDING_STATUS_FILE
      #     value: "/config/pia_port.txt"
      #   - name: VPN_SERVICE_PROVIDER
      #     value: "private internet access"
      #   volumeMounts:
      #   - name: tun
      #     mountPath: /dev/net/tun
      #   - name: config
      #     mountPath: /config
      nodeSelector:
        kubernetes.io/hostname: catuai
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      volumes:
      # - name: tun
      #   hostPath:
      #     path: /dev/net/tun
      - name: scripts
        configMap:
          name: transmission-scripts
          defaultMode: 0755
      - name: config
        hostPath:
          path: /mnt/transmission
      - name: watch
        hostPath:
          path: /mnt/transmission/watch
          type: DirectoryOrCreate
      - name: downloads
        persistentVolumeClaim:
          claimName: downloads-pvc