apiVersion: apps/v1
kind: Deployment
metadata:
  name: transmission
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: transmission
      app.kubernetes.io/name: transmission
  template:
    metadata:
      labels:
        app: transmission
        app.kubernetes.io/name: transmission
        app.kubernetes.io/part-of: streaming-stack
      annotations:
        app.kubernetes.io/documentation: "https://docs.linuxserver.io/images/docker-transmission/"
        vault.hashicorp.com/agent-inject: "true"
        #
        ## --- Transmission
        #
        vault.hashicorp.com/role: vault
        vault.hashicorp.com/agent-inject-secret-transmission: "secret/data/transmission"
        vault.hashicorp.com/agent-inject-template-transmission: |
          {{- with secret "secret/data/transmission" -}}
          {{ .Data.data.USERNAME | writeToFile "/vault/secrets/user" "vault" "1000" "0640" }}
          {{ .Data.data.PASSWORD | writeToFile "/vault/secrets/password" "vault" "1000" "0640" }}
          {{- end -}}

          {{- with secret "secret/data/ntfy" -}}
          {{ .Data.data.ADMIN_TOKEN | writeToFile "/vault/secrets/ntfy" "vault" "1000" "0640" }}
          {{- end -}}
    spec:
      dnsPolicy: ClusterFirst
      serviceAccountName: transmission
      containers:
      - name: transmission
        image: lscr.io/linuxserver/transmission:latest
        ports:
        - containerPort: 9091
          name: webui
          protocol: TCP
        env:
        - name: "FILE__USER"
          value: "/vault/secrets/user"
        - name: "FILE__PASS"
          value: "/vault/secrets/password"
        # Base Config
        - name: TRANSMISSION_DOWNLOAD_DIR
          value: "/downloads"
        # Automation
        - name: TRANSMISSION_SCRIPT_TORRENT_ADDED_ENABLED
          value: "true"
        - name: TRANSMISSION_SCRIPT_TORRENT_ADDED_FILENAME
          value: "/scripts/added.sh"
        - name: TRANSMISSION_SCRIPT_TORRENT_DONE_ENABLED
          value: "true"
        - name: TRANSMISSION_SCRIPT_TORRENT_DONE_FILENAME
          value: "/scripts/finished.sh"
        - name: TRANSMISSION_SCRIPT_TORRENT_DONE_SEEDING_ENABLED
          value: "true"
        - name: TRANSMISSION_SCRIPT_TORRENT_DONE_SEEDING_FILENAME
          value: "/scripts/completed.sh"
        # Ratios & Queue
        - name: TRANSMISSION_INCOMPLETE_DIR_ENABLED
          value: "false"
        - name: TRANSMISSION_RENAME_PARTIAL_FILES
          value: "false"
        - name: TRANSMISSION_RATIO_LIMIT
          value: "3.0"
        - name: TRANSMISSION_RATIO_LIMIT_ENABLED
          value: "true"
        - name: TRANSMISSION_DOWNLOAD_QUEUE_ENABLED
          value: "false"
        - name: TRANSMISSION_SEED_QUEUE_ENABLED
          value: "false"
        - name: TRANSMISSION_DOWNLOAD_QUEUE_SIZE
          value: "999"
        - name: TRANSMISSION_SEED_QUEUE_SIZE
          value: "999"
        # Networking
        - name: TRANSMISSION_PEER_PORT_RANDOM_ON_START
          value: "true"
        - name: TRANSMISSION_PEER_LIMIT_PER_TORRENT
          value: "20"
        envFrom:
        - configMapRef:
            name: streaming-stack-config
        resources:
          requests:
            cpu: 50m
            memory: 256Mi
          limits:
            cpu: 200m
            memory: 512Mi
        volumeMounts:
        - name: scripts
          mountPath: /custom-cont-init.d/01-setup-config.sh
          subPath: 01-setup-config.sh
        - name: scripts
          mountPath: /scripts
        - name: config
          mountPath: /config
        - name: downloads
          mountPath: /downloads
      nodeSelector:
        kubernetes.io/hostname: catimore
      volumes:
      - name: scripts
        configMap:
          name: transmission-scripts
          defaultMode: 0755
      - name: config
        hostPath:
          path: /mnt/transmission
          type: DirectoryOrCreate
      - name: watch
        hostPath:
          path: /mnt/transmission/watch
          type: DirectoryOrCreate
      - name: downloads
        persistentVolumeClaim:
          claimName: downloads-pvc