apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: streaming

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: transmission-scripts
  files:
  - scripts/01-setup-config.sh
  - scripts/added.sh
  - scripts/finished.sh
  - scripts/completed.sh

- name: transmission-jobs
  files:
  - scripts/tagger-daemon.sh
  - scripts/check-port-daemon.sh

resources:
- sa.yaml
- deployment.yaml
- svc.yaml
- ingress.yaml
- cronjobs/check-port.yaml
- cronjobs/tagger.yaml