apiVersion: v1
kind: Service
metadata:
  name: transmission
spec:
  selector:
    app: transmission
  ports:
  - name: webui
    port: 9091
    targetPort: 9091
    protocol: TCP
  - name: tcp
    port: 51413
    targetPort: 51413
    protocol: TCP
  - name: udp
    port: 51413
    targetPort: 51413
    protocol: UDP
---
apiVersion: v1
kind: Service
metadata:
  name: transmission-lb
  annotations:
    external-dns.alpha.kubernetes.io/hostname: transmission.lan
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.36
  ports:
  - name: webui
    port: 80
    targetPort: 9091
    protocol: TCP
  - name: tcp
    port: 51413
    targetPort: 51413
    protocol: TCP
  - name: udp
    port: 51413
    targetPort: 51413
    protocol: UDP
  selector:
    app: transmission