apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
spec:
  replicas: 0
  selector:
    matchLabels:
      app: plex
      app.kubernetes.io/name: plex
  template:
    metadata:
      labels:
        app: plex
        app.kubernetes.io/name: plex
        app.kubernetes.io/part-of: streaming-stack
    spec:
      containers:
        - name: plex
          image: lscr.io/linuxserver/plex:latest
          env:
          - name: VERSION
            value: "docker"
          - name: PLEX_CLAIM
            value: claim-DQMsWFNz7TrFNEzV921y
          - name: LIBVA_DRIVER_NAME
            value: "iHD"
          envFrom:
          - configMapRef:
              name: streaming-stack-config
          ports:
            - containerPort: 32400
          volumeMounts:
            - name: config
              mountPath: /config
            - name: dri
              mountPath: /dev/dri
            - name: movies
              mountPath: /movies
            - name: series
              mountPath: /tv
      nodeSelector:
        kubernetes.io/hostname: castillo
      volumes:
        - name: dri
          hostPath:
            path: /dev/dri
        - name: config
          hostPath:
            path: /mnt/plex
            type: DirectoryOrCreate
        - name: movies
          persistentVolumeClaim:
            claimName: movies-pvc
        - name: series
          persistentVolumeClaim:
            claimName: series-pvc