apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plex
      app.kubernetes.io/name: plex
  template:
    metadata:
      labels:
        app: plex
        app.kubernetes.io/name: plex
        app.kubernetes.io/part-of: streaming-stack
    spec:
      hostNetwork: true
      containers:
        - name: plex
          image: lscr.io/linuxserver/plex:latest
          env:
          - name: VERSION
            value: "docker"
          - name: PLEX_CLAIM
            value: claim-8iEtGSFKQecs_W5AHFQ5
          - name: LIBVA_DRIVER_NAME
            value: "iHD"
          envFrom:
          - configMapRef:
              name: streaming-stack-config
          ports:
          - containerPort: 32400
          securityContext:
            privileged: true
            allowPrivilegeEscalation: false
            capabilities:
              add: ["SYS_RAWIO", "SETPCAP", "SYS_ADMIN"]
          volumeMounts:
          - name: dri
            mountPath: /dev/dri
            readOnly: false
          - name: transcodes
            mountPath: /cache/transcodes
          - name: config
            mountPath: /config
          - name: media
            mountPath: /media
      nodeSelector:
        kubernetes.io/hostname: castillo
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        # Group id (992) can be found running 
        # getent group render | cut -d: -f3
        supplementalGroups: [44, 107, 992]
      volumes:
      - name: dri
        hostPath:
          path: /dev/dri
      - name: transcodes
        emptyDir:
          medium: Memory
          sizeLimit: 4Gi
      - name: config
        hostPath:
          path: /mnt/plex
          type: DirectoryOrCreate
      - name: media
        hostPath:
          path: /media
          type: DirectoryOrCreate