kind: HTTPScaledObject
apiVersion: http.keda.sh/v1alpha1
metadata:
  name: linkstack
  namespace: media
  annotations:
    httpscaledobject.keda.sh/skip-scaledobject-creation: "false"
spec:
  hosts:
  - linkstack.local
  - linkstack.lan
  - linkstack.citocafecito.work
  - linkstack-proxy
  scaleTargetRef:
    kind: Deployment
    name: linkstack
    service: linkstack
    port: 80
  replicas:
    min: 0
    max: 3
  scaledownPeriod: 60
  scalingMetric:
    requestRate:
      granularity: 1s
      targetValue: 1
      window: 1m