apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: linkstack
  namespace: media
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: keda-http@kubernetescrd
    traefik.ingress.kubernetes.io/router.timeout: 120s
spec:
  rules:
  - host: linkstack.lan
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: keda-add-ons-http-interceptor-proxy
            port:
              number: 8080
