apiVersion: apps/v1
kind: Deployment
metadata:
  name: yt-ytdl-pot
  namespace: media
  labels:
    tier: disposable
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ytdl-pot
  template:
    metadata:
      labels:
        app: ytdl-pot
    spec:
      hostNetwork: false
      automountServiceAccountToken: false
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: NotIn
                values:
                - catimore
      containers:
      # Sidecar de VPN
      # - name: vpn
      #   image: qmcgaw/gluetun:latest
      #   securityContext:
      #     capabilities:
      #       add:
      #         - NET_ADMIN
      #     allowPrivilegeEscalation: false
      #   env:
      #     - name: VPN_SERVICE_PROVIDER
      #       value: "custom" # Cambiar según tu proveedor (wireguard, protonvpn, mullvad, etc.)
      #     - name: VPN_TYPE
      #       value: "wireguard"
      #     # Agrega aquí tus credenciales/configuración de entorno de Gluetun
      #   ports:
      #     - containerPort: 4416
      #       name: pot-port
      #   resources:
      #     limits:
      #       cpu: "100m"
      #       memory: "128Mi"
      #     requests:
      #       cpu: "20m"
      #       memory: "32Mi"

      # Generador POT
      - name: generator
        image: brainicism/bgutil-ytdlp-pot-provider:latest
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
        resources:
          limits:
            cpu: "200m"
            memory: "256Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
      securityContext:
        seccompProfile:
          type: RuntimeDefault
---
apiVersion: v1
kind: Service
metadata:
  name: ytdl-pot
  namespace: media
spec:
  selector:
    app: ytdl-pot
  ports:
    - protocol: TCP
      port: 4416
      targetPort: 4416