apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# Shared components
- ../../../components/playlists
- middleware.yaml

# Jellyfin Server
- server-deployment.yaml
- server-svc.yaml
- server-ingress.yaml

# Jellyfin User Administrator
- jfa-deployment.yaml
- jfa-svc.yaml
- jfa-ingress.yaml