apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: jellyfin-config
  files:
  - config/branding.xml
  - config/livetv.xml

- name: jellyfin-web
  files:
  - branding.css=web/branding.css

resources:
# Shared components
- ../../../components/playlists
- middleware.yaml

# Jellyfin Server
- server-deployment.yaml
- server-svc.yaml
- server-ingress.yaml

# Jellyfin User Administrator
- jfa-deployment.yaml
- jfa-svc.yaml
- jfa-ingress.yaml