apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  namespace: streaming
  labels:
    app: jellyfin
    app.kubernetes.io/name: jellyfin
    app.kubernetes.io/part-of: streaming-stack
spec:
  selector:
    app: jellyfin
  ports:
  - name: http
    port: 8096
    targetPort: 8096