apiVersion: v1
kind: Service
metadata:
  name: mydrive
  labels:
    app.kubernetes.io/name: mydrive
spec:
  selector:
    app.kubernetes.io/name: mydrive
  ports:
  - name: http
    port: 3000
    targetPort: 3000
  - name: https
    port: 8080
    targetPort: 8080
