apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: streaming

configMapGenerator:
- name: lidarr-scripts
  files: 
  - scripts/common.sh
  - scripts/01-setup-config.sh
  - scripts/album-added.sh
  - scripts/bpm-calculator.sh

resources:
- deployment.yaml
- svc.yaml
- ingress.yaml