apiVersion: v1
kind: Service
metadata:
  name: cloudflare-solver
  labels:
    app: cloudflare-solver
    app.kubernetes.io/name: cloudflare-solver
    app.kubernetes.io/part-of: streaming-stack
spec:
  selector:
    app: cloudflare-solver
  ports:
  - name: http
    port: 8000
    targetPort: 8000