apiVersion: batch/v1
kind: CronJob
metadata:
  name: qbittorrent-port-updater
  namespace: streaming
spec:
  schedule: "0 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: updater
              image: curlimages/curl:latest
              command: ["/bin/sh", "/scripts/check-port-daemon.sh"]
              env:
              - name: QBITTORRENT_URL
                value: "http://qbittorrent.streaming.svc.cluster.local"
              - name: API_KEY
                valueFrom:
                  secretKeyRef:
                    name: qbittorrent
                    key: token
              volumeMounts:
              - name: script-volume
                mountPath: /scripts/check-port-daemon.sh
                subPath: check-port-daemon.sh
              - name: config
                mountPath: /config/qBittorrent
          nodeSelector:
            kubernetes.io/hostname: catimore
          volumes:
          - name: script-volume
            configMap:
              name: qbittorrent-port-updater
              defaultMode: 0755
          - name: config
            hostPath:
              path: /mnt/qbittorrent
              type: DirectoryOrCreate 