apiVersion: v1
kind: ConfigMap
metadata:
  name: dispatcharr-config
data:
  # ───────────────
  # Dispatcharr
  # ───────────────
  DISPATCHARR_ENABLE_TRANSCODING: "true"
  DISPATCHARR_HW_ACCEL: "qsv"
  DISPATCHARR_TRANSCODE_CODEC: "h264"
  DISPATCHARR_ENV: modular
  LIBVA_DRIVER_NAME: iHD
  SECRET_KEY: b11724a9ebd09b5924f28bc2728b0e1d739349daa57a7708dc90eb080a387de1

  # ───────────────
  # PostgreSQL
  # ───────────────
  POSTGRES_DB: dispatcharr
  POSTGRES_HOST: dispatcharr-postgresql
  POSTGRES_PASSWORD: superpassword
  POSTGRES_PORT: "5432"
  POSTGRES_USER: dispatcharr

  # ───────────────
  # Redis / Valkey
  # ───────────────
  REDIS_HOST: dispatcharr-valkey
  REDIS_PORT: "6379"

  # ───────────────
  # Celery Broker
  # ───────────────
  CELERY_BROKER_URL: redis://dispatcharr-valkey:6379/0
  CELERY_RESULT_BACKEND: redis://dispatcharr-valkey:6379/0