# kustomizations/monitoring/kite.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kite
  namespace: monitoring
  labels:
    app.kubernetes.io/name: kite
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kite
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kite
    spec:
      containers:
        - name: kite
          image: ghcr.io/zxh326/kite:v0.9.0
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: DB_TYPE
              value: sqlite
            - name: DB_DSN
              value: /data/kite.db
            - name: ANONYMOUS_USER_ENABLED
              value: 'true'
          volumeMounts:
            - name: kite-storage
              mountPath: /data
      nodeSelector:
        kubernetes.io/hostname: catuai
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      volumes:
        - name: kite-storage
          hostPath:
            path: /mnt/kite
            type: DirectoryOrCreate