apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- prometheus.yaml
- kite.yaml
- filebrowser.yaml
- glances.yaml
- ingress.yaml

namespace: monitoring

# patches: 
#   - path: patches/insecure-tls-patch.yaml