apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellystat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellystat
      app.kubernetes.io/name: jellystat
  template:
    metadata:
      labels:
        app: jellystat
        app.kubernetes.io/name: jellystat
      annotations:
        app.kubernetes.io/documentation: "https://github.com/CyferShepard/Jellystat"
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: vault
        vault.hashicorp.com/agent-inject-secret-jellystat: "secret/data/jellystat"
        vault.hashicorp.com/agent-inject-template-jellystat: |
          {{- with secret "secret/data/jellystat" -}}
          {{ .Data.data.JWT_SECRET | writeToFile "/vault/secrets/jwt" "vault" "vault" "0600" }}
          {{ .Data.data.ADMIN_USER | writeToFile "/vault/secrets/user" "vault" "vault" "0600" }}
          {{ .Data.data.ADMIN_PASS | writeToFile "/vault/secrets/password" "vault" "vault" "0600" }}
          {{- end -}}
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: jellystat
        image: ghcr.io/cyfershepard/jellystat:latest
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: jellystat-database
        - configMapRef:
            name: jellystat-config
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 500m          
            memory: 1024Mi
