apiVersion: v1
kind: PersistentVolume
metadata:
  name: suwayomi-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  hostPath:
    path: /mnt/suwayomi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: suwayomi-pvc
  namespace: media
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ""
  volumeName: suwayomi-pv
