apiVersion: v1
kind: Service
metadata:
  name: suwayomi
  labels:
    app.kubernetes.io/name: suwayomi
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: suwayomi
  ports:
  - name: http
    protocol: TCP
    port: 4567
    targetPort: 4567
    nodePort: 30080
