apiVersion: apps/v1
kind: Deployment
metadata:
  name: deluge
  labels:
    app: deluge
    app.kubernetes.io/name: deluge
    app.kubernetes.io/instance: streaming-stack
    app.kubernetes.io/part-of: streaming-stack
spec:
  replicas: 0
  selector:
    matchLabels:
      app: deluge
      app.kubernetes.io/name: deluge
      app.kubernetes.io/instance: streaming-stack
      app.kubernetes.io/part-of: streaming-stack
  template:
    metadata:
      labels:
        app: deluge
        app.kubernetes.io/name: deluge
        app.kubernetes.io/instance: streaming-stack
        app.kubernetes.io/part-of: streaming-stack
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "vault"
        vault.hashicorp.com/agent-inject-secret-secrets: "secret/data/deluge"
        vault.hashicorp.com/agent-inject-template-secrets: |
          {{- with secret "secret/data/deluge" -}}
          {{ .Data.data.USER | writeToFile "/vault/secrets/user" "vault" "vault" "0600" }}
          {{ .Data.data.PASS | writeToFile "/vault/secrets/pass" "vault" "vault" "0600" }}
          {{- end -}}
    spec:
      containers:
      - name: deluge
        image: lscr.io/linuxserver/deluge:latest
        env:
        - name: DELUGE_USER__MYVAR
          value: /vault/secrets/user
        - name: DELUGE_PASS__MYVAR
          value: /vault/secrets/pass
        - name: DELUGE_LOGLEVEL
          value: warning
        envFrom:
        - configMapRef:
            name: streaming-stack-config
        ports:
        - containerPort: 8112
          name: webui
        volumeMounts:
        - name: config
          mountPath: /config
        - name: downloads
          mountPath: /downloads
      nodeSelector:
        kubernetes.io/hostname: castillo
      volumes:
      - name: config
        hostPath:
          path: /mnt/deluge
          type: DirectoryOrCreate
      - name: downloads
        persistentVolumeClaim:
          claimName: downloads-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: deluge
spec:
  ports:
    - port: 8112
      targetPort: 8112
      name: webui
    - port: 6881
      targetPort: 6881
      protocol: TCP
      name: torrent-tcp
    - port: 6881
      targetPort: 6881
      protocol: UDP
      name: torrent-udp
  selector:
    app: deluge
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: deluge
spec:
  rules:
  - host: deluge.citocafecito.work
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: deluge
              port:
                number: 8112