apiVersion: apps/v1
kind: Deployment
metadata:
  name: nzbget
spec:
  replicas: 0
  selector:
    matchLabels:
      app: nzbget
      app.kubernetes.io/name: nzbget
      app.kubernetes.io/instance: streaming-stack
      app.kubernetes.io/part-of: streaming-stack
  template:
    metadata:
      labels:
        app: nzbget
        app.kubernetes.io/name: nzbget
        app.kubernetes.io/instance: streaming-stack
        app.kubernetes.io/part-of: streaming-stack
      annotations:
        app.kubernetes.io/documentation: "https://hub.docker.com/r/linuxserver/nzbget"
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "vault"
        vault.hashicorp.com/agent-inject-secret-secrets: "secret/data/nzbget"
        vault.hashicorp.com/agent-inject-template-secrets: |
          {{- with secret "secret/data/nzbget" -}}
          {{ .Data.data.USER | writeToFile "/vault/secrets/user" "vault" "vault" "0600" }}
          {{ .Data.data.PASS | writeToFile "/vault/secrets/pass" "vault" "vault" "0600" }}
          {{- end -}}
    spec:
      containers:
      - name: nzbget
        image: lscr.io/linuxserver/nzbget:latest
        env:
        - name: FILE__NZBGET_USER
          value: /vault/secrets/user
        - name: FILE__NZBGET_PASS
          value: /vault/secrets/pass
        envFrom:
        - configMapRef:
            name: streaming-stack-config
        ports:
        - containerPort: 6789
        volumeMounts:
        - name: config
          mountPath: /config
        - name: downloads
          mountPath: /downloads
      nodeSelector:
        kubernetes.io/hostname: castillo
      volumes:
      - name: config
        hostPath:
          path: /mnt/nzbget
          type: DirectoryOrCreate
      - name: downloads
        persistentVolumeClaim:
          claimName: downloads-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: nzbget
spec:
  selector:
    app: nzbget
  ports:
  - name: webui
    port: 6789
    targetPort: 6789
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nzbget
spec:
  rules:
    - host: nzbget.lan
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nzbget
                port:
                  number: 6789