apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.2.1/standard-install.yaml
  - gateway-class.yaml
  - gateway.yaml
  - https://github.com/kserve/kserve/releases/download/v0.17.0/kserve.yaml
  - https://github.com/kserve/kserve/releases/download/v0.17.0/kserve-cluster-resources.yaml

patches:
  - path: patches/kserve-config-patch.yaml
    target:
      kind: ConfigMap
      name: inferenceservice-config

namespace: kserve