apiVersion: apps/v1
kind: Deployment
metadata:
  name: byparr
  labels:
    app: byparr
    app.kubernetes.io/name: byparr
    tier: disposable
spec:
  replicas: 0
  selector:
    matchLabels:
      app: byparr
      app.kubernetes.io/name: byparr
  template:
    metadata:
      labels:
        app: byparr
        app.kubernetes.io/name: byparr
    spec:
      terminationGracePeriodSeconds: 30
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: NotIn
                values:
                - caturra
                - catimore
      containers:
      - name: byparr
        image: ghcr.io/thephaseless/byparr:latest
        ports:
        - containerPort: 8000
        env:
        - name: BROWSER_LOCALE
          value: "es-CO"
        - name: TZ
          value: "America/Bogota"
        - name: LOG_LEVEL
          value: 'info'
        resources:
          requests:
            cpu: 50m
            memory: 512Mi
            ephemeral-storage: 2Gi
          limits:
            cpu: 2
            memory: 4Gi
            ephemeral-storage: 3Gi
        volumeMounts:
        - name: dshm
          mountPath: /dev/shm
        - name: tmp
          mountPath: /tmp
        - name: cache
          mountPath: /cache
      tolerations:
      - key: node-role.control-plane
        operator: Exists
        effect: NoSchedule
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
          sizeLimit: 1Gi
      - name: tmp
        emptyDir:
          medium: Memory
          sizeLimit: 3Gi
      - name: cache
        emptyDir:
          medium: Memory
          sizeLimit: 1Gi