apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: shared-playlists
    files:
      # Smart
      - smarts/supermix.nsp
      - smarts/supersupermix.nsp
      - smarts/mamalonas.nsp
      - smarts/forgotten.nsp
      - smarts/discovery.nsp
      - smarts/top_1980s.nsp
      - smarts/top_1990s.nsp
      - smarts/top_2000s.nsp
      - smarts/top_2010s.nsp
      - smarts/top_2020s.nsp

      # Manual
      - angra/Angra-Temple-of-Shadows-20th-Anniversary-Tour.m3u
      - angra/Angra-The-Cycles-of-Rebirth.m3u
      - angra/Angra-The-Favorites-Anthology.m3u
      - helloween/Helloween-40-years-tour.m3u
      - iron-maiden/Iron-Maiden-Future-Past-Tour.m3u
      - iron-maiden/Iron-Maiden-Run-For-Your-Lives.m3u
      - iron-maiden/Iron-Maiden-The-Heritage-of-the-Beast.m3u
      - stratovarius/Stratovarius-Best-Of.m3u
      - stratovarius/Stratovarius-Calle-13-bar-bogota-colombia-2025.m3u
      - stratovarius/Stratovarius-Melodic-Ballads.m3u