apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: glances
spec:
  selector:
    matchLabels:
      app: glances
      app.kubernetes.io/name: glances
  template:
    metadata:
      labels:
        app: glances
        app.kubernetes.io/name: glances
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "vault"
        vault.hashicorp.com/agent-inject-secret-glances.conf: "secret/data/ntfy"
        vault.hashicorp.com/agent-inject-template-glances.conf: |
          {{- with secret "secret/data/ntfy" -}}
          [global]
          check_interval=60

          [network]
          # Ignorar interfaces virtuales de Kubernetes que rompen la API
          hide=lo,veth.*,cni.*,flannel.*,calico.*,tun.*

          [outputs]
          global_limits=TRUE

          [webhooks]
          url=http://ntfy.core.svc.cluster.local/glances
          method=POST
          headers=Title:Alerta de Sistema en Glances,Tags:warning,Authorization: Bearer {{ .Data.data.ADMIN_TOKEN }}
          body={"topic": "glances", "title": "Glances {{ "{{type}}" }} en {{ "{{hostname}}" }}", "message": "El recurso {{ "{{plugin}}" }} superó el límite: {{ "{{msg}}" }}", "tags": ["warning"]}
          {{- end -}}
    spec:
      hostPID: true
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: glances
        image: nicolargo/glances:latest
        env:
        - name: GLANCES_OPT
          value: "-w -B 0.0.0.0 -C /vault/secrets/glances.conf --disable-plugin processlist,docker,containers,irq --fs-free-space"
        ports:
        - containerPort: 61208
          hostPort: 61208
        resources:
          requests:
            cpu: 100m
            memory: 32Mi
          limits:
            cpu: 500m
            memory: 256Mi
        volumeMounts:
        - name: host-root
          mountPath: /host
          readOnly: true
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      volumes:
        - name: host-root
          hostPath:
            path: /