apiVersion: v1
kind: ConfigMap
metadata:
  name: esphome-config
  namespace: home-assistant
data:
  proxy.yaml: |
    esphome:
      name: proxy-segundo-piso

    # Para que funcione en un PC Linux como proxy, 
    # se usa el componente nativo de bluetooth
    bluetooth:

    esp32_ble_tracker:

    
    # Enable logging
    logger:

    # Enable Home Assistant API
    api:
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: esphome
  namespace: home-assistant
  labels:
    app.kubernetes.io/name: esphome
    app.kubernetes.io/part-of: home-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: esphome
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: esphome
    spec:
      hostNetwork: true
      nodeSelector:
        kubernetes.io/hostname: caturra
      containers:
      - name: esphome
        image: esphome/esphome:latest
        ports:
        - containerPort: 6052
          name: dashboard
        - containerPort: 6053
          name: api
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "200m"
            memory: "128Mi"
        securityContext:
          privileged: true
        volumeMounts:
          - name: usb
            mountPath: /dev/bus/usb
          - name: dbus-socket
            mountPath: /var/run/dbus
          - name: config
            mountPath: /config/proxy.yaml
            subPath: proxy.yaml
      volumes:
        - name: usb
          hostPath:
            path: /dev/bus/usb
            type: Directory
        - name: dbus-socket
          hostPath:
            path: /var/run/dbus
            type: Directory
        - name: config
          configMap:
            name: esphome-config
            items:
              - key: proxy.yaml
                path: proxy.yaml