apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
data:
  mosquitto.conf: |
    listener 1883 0.0.0.0
    allow_anonymous true
    persistence false
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
      app.kubernetes.io/name: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
        app.kubernetes.io/name: mosquitto
    spec:
      containers:
      - name: mosquitto
        image: eclipse-mosquitto
        ports:
        - containerPort: 1883
        - containerPort: 9001
        resources:
          requests:
            cpu: 1m
            memory: 64Mi
          limits:
            cpu: 10m
            memory: 128Mi
        securityContext:
          privileged: true
        volumeMounts:
        - name: config
          mountPath: /mosquitto/config
          readOnly: false
      volumes:
      - name: config
        configMap:
          name: mosquitto-config
---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  annotations:
    external-dns.alpha.kubernetes.io/hostname: mosquitto.lan
  labels:
    app: mosquitto
    app.kubernetes.io/name: mosquitto
spec:
  loadBalancerIP: 192.168.1.20
  type: LoadBalancer
  selector:
    app: mosquitto
    app.kubernetes.io/name: mosquitto
  ports:
  - name: mqtt
    protocol: TCP
    port: 1883
    targetPort: 1883
  - name: http
    protocol: TCP
    port: 9001
    targetPort: 9001