apiVersion: apps/v1
kind: Deployment
metadata:
  name: openwakeword
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openwakeword
  template:
    metadata:
      labels:
        app: openwakeword
    spec:
      containers:
      - name: openwakeword
        image: rhasspy/wyoming-openwakeword:latest
        args:
          - "--preload-model"
          - "eddie"
          - "--uri"
          - "tcp://0.0.0.0:10400"
        ports:
        - containerPort: 10400
---
apiVersion: v1
kind: Service
metadata:
  name: openwakeword
spec:
  selector:
    app: openwakeword
  ports:
  - name: wyoming
    port: 10400
    targetPort: 10400