apiVersion: v1
kind: PersistentVolume
metadata:
  name: piper-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /mnt/piper
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: piper-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: piper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: piper
      app.kubernetes.io/name: piper
  template:
    metadata:
      labels:
        app: piper
        app.kubernetes.io/name: piper
    spec:
      containers:
      - name: piper
        image: lscr.io/linuxserver/piper:latest
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "America/Bogota"
        # Voices can be found here https://rhasspy.github.io/piper-samples/#es_MX-ald-medium
        - name: PIPER_VOICE
          value: "es_MX-claude-high"
        ports:
        - containerPort: 10200
        resources:
          requests:
            cpu: "100m"
            memory: "512Mi"
          limits:
            cpu: "2"
            memory: "2Gi"
        volumeMounts:
        - name: piper-config
          mountPath: /config
        - name: tmp-cache
          mountPath: /tmp
      nodeSelector:
        kubernetes.io/hostname: castillo
      volumes:
      - name: piper-config
        persistentVolumeClaim:
          claimName: piper-pvc
      - name: tmp-cache
        emptyDir:
          medium: Memory
---
apiVersion: v1
kind: Service
metadata:
  name: piper
spec:
  selector:
    app: piper
  ports:
  - name: http
    port: 10200
    targetPort: 10200
