apiVersion: v1
kind: PersistentVolume
metadata:
  name: piper-pv
spec:
  capacity:
    storage: 1Gi
  accessModes: [ "ReadWriteOnce" ]
  hostPath:
    path: /mnt/piper
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: piper-pvc
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: piper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: piper
      app.kubernetes.io/name: piper
  template:
    metadata:
      labels:
        app: piper
        app.kubernetes.io/name: piper
    spec:
      containers:
      - name: piper
        image: lscr.io/linuxserver/piper:latest
        env:
        - name: PUID
          value: "1000"
        - name: PUID
          value: "1000"
        - name: TZ
          value: "America/Bogota
        - name: PIPER_VOICE
          value: "es_MX-claude-high"
        ports:
        - containerPort: 10200
        volumeMounts:
        - name: piper-config
          mountPath: /config
      nodeSelector:
        kubernetes.io/hostname: castillo
      volumes:
      - name: piper-config
        persistentVolumeClaim:
          claimName: piper-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: piper
spec:
  selector:
    app: piper
  ports:
  - name: http
    port: 10200
    targetPort: 10200
