apiVersion: apps/v1
kind: Deployment
metadata:
  name: ring-mqtt
  labels:
    app: ring-mqtt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ring-mqtt
  template:
    metadata:
      labels:
        app: ring-mqtt
        app.kubernetes.io/name: ring-mqtt
        app.kubernetes.io/part-of: home-assistant
    spec:
      containers:
      - name: ring-mqtt
        image: tsightler/ring-mqtt:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 51824
          name: web-ui
        - containerPort: 55123
          name: auth-ui
        - containerPort: 8554
          name: rtsp
        volumeMounts:
        - name: data
          mountPath: /data
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 300m
            memory: 512Mi
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      volumes:
      - name: data
        nfs:
          server: 192.168.1.10
          path: /mnt/ring-mqtt
---
apiVersion: v1 
kind: Service
metadata:
  name: ring-mqtt
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 51824
    targetPort: 51824
    name: web-ui
  - protocol: TCP
    port: 55123
    targetPort: 55123
    name: auth-ui
  # Nedded for Home Assistant Stateless connection
  # E.g.: rtsp://username:password@ring-mqtt.home-assistant.svc.cluster.local:8554/camid_live
  - protocol: TCP
    port: 8554
    targetPort: 8554
    name: rtsp
  selector:
    app: ring-mqtt
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ring-mqtt
spec:
  rules:
  - host: ringmqtt.lan
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: ring-mqtt
              port:
                number: 55123
