apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- pi-hole
- external-dns
# - kea-dhcp
- avahi-daemon.yaml
# - speedtest.yaml

# - middlewares/local-only.yaml
# - middlewares/block-metrics.yaml

namespace: networking
