apiVersion: v1
kind: ConfigMap
metadata:
  name: pihole-custom-dns
data:
  10-custom-dns.conf: |
    address=/impresora.lan/192.168.1.254
    address=/pneuma.lan/192.168.1.220
    address=/jellyfin.lan/192.168.1.231
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pihole
      app.kubernetes.io/name: pihole
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: pihole
        app.kubernetes.io/name: pihole
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "vault"
        vault.hashicorp.com/agent-inject-secret-admin_password: "secret/data/pihole"
        vault.hashicorp.com/agent-inject-template-admin_password: |
          {{- with secret "secret/data/pihole" -}}
          {{ .Data.data.ADMIN_PASSWORD }}
          {{- end }}
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      terminationGracePeriodSeconds: 10
      containers:
      - name: pihole
        image: pihole/pihole:2025.10.0
        env:
        - name: DNSMASQ_LISTENING
          value: all
        - name: FTLCONF_misc_etc_dnsmasq_d
          value: "true"
        - name: TZ
          value: "America/Bogota"
        - name: FTLCONF_dns_revServers
          value: 'true,192.168.0.0/16,192.168.0.1'
        - name: FTLCONF_dns_upstreams
          value: '1.1.1.1,1.0.0.1,8.8.8.8,8.8.4.4'
        - name: WEBPASSWORD_FILE
          value: "/vault/secrets/admin_password"
        ports:
        - name: dns-tcp
          containerPort: 53
          protocol: TCP
        - name: dns-udp
          containerPort: 53
          protocol: UDP
        - name: http
          containerPort: 8080
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 128Mi
        securityContext:
          capabilities:
            # drop:
            # - ALL
            add:
            - NET_ADMIN
            - CAP_NET_BIND_SERVICE
            - CAP_NET_RAW
            - CAP_CHOWN
            - SYS_TIME
            - SYS_NICE
        volumeMounts:
        - name: pihole-etc
          mountPath: /etc/pihole
        - name: custom-dns
          mountPath: /etc/dnsmasq.d
      volumes:
      - name: pihole-etc
        emptyDir: {}
      - name: custom-dns
        configMap:
          name: pihole-custom-dns
---
apiVersion: v1
kind: Service
metadata:
  name: pihole
  labels:
    app: pihole
spec:
  ports:
  - name: dns-udp
    port: 53
    protocol: UDP
    targetPort: 53
  - name: dns-tcp
    port: 53
    protocol: TCP
    targetPort: 53
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: pihole
