apiVersion: v1
kind: PersistentVolume
metadata:
  name: ntfy-postgresql-pv
spec:
  capacity:
    storage: "5Gi"
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /mnt/ntfy-postgresql
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ntfy-postgresql-pvc
  namespace: media
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: "5Gi"
  storageClassName: ""
  volumeName: ntfy-postgresql-pv
