name: Deploy Kustomizations

on:
  push:
    branches:
      - main
    paths:
      - "kustomizations/**"
      - ".github/workflows/kustomizations.yaml"

jobs:
  deploy:
    runs-on: [self-hosted, arc, k8s]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - uses: yokawasa/action-setup-kube-tools@v0.13.5
        with:
          setup-tools: |
            kubectl
            helm
            kustomize
          kubectl: '1.33.4'
          helm: '3.18.6'
          kustomize: '5.6.0'

      - name: Apply Kustomizations
        run: |
          kubectl  apply -k kustomizations

      - name: Notify ntfy
        if: always()
        run: |
          # Definir variables dinámicas según el estado del job
          if [ "${{ job.status }}" = "success" ]; then
            STATUS_TITLE="✅ Deployment Exitoso"
            STATUS_TAGS="white_check_mark,kubernetes"
            STATUS_PRIORITY="default"
          else
            STATUS_TITLE="❌ Deployment Fallido"
            STATUS_TAGS="x,rotating_light"
            STATUS_PRIORITY="high"
          fi

          # Enviar la notificación vía curl usando tu token de Vault expuesto en GitHub Secrets
          curl -H "Authorization: Bearer ${{ secrets.NTFY_TOKEN }}" \
               -H "Title: ${STATUS_TITLE}" \
               -H "Tags: ${STATUS_TAGS}" \
               -H "Priority: ${STATUS_PRIORITY}" \
               -H "Actions: view, Ver Logs, ${RUN_URL}" \
               -H "X-Repository: ${{ github.repository }}" \
               -H "X-Commit: ${{ github.sha }}" \
               -d "El workflow de GitOps para kustomizations ha terminado con estado: ${{ job.status }}." \
               http://ntfy.core.svc.cluster.local/github-actions